// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Questionnaire.Infrastructure.Persistence.Postgres;

#nullable disable

namespace Questionnaire.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230530074121_PersistBogus")]
    partial class PersistBogus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SurveyQuestionQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveyQuestionSurveyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionSurveyId", "SurveyQuestionQuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e"),
                            Advice = "memberikan kesempatan bertanya di dalam kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di dalam kelas?"
                        },
                        new
                        {
                            Id = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9"),
                            Advice = "memberikan kesempatan bertanya di luar kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di luar kelas?"
                        },
                        new
                        {
                            Id = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803"),
                            Advice = "memanfaatkan fitur forum yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur forum e-learning?"
                        },
                        new
                        {
                            Id = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f"),
                            Advice = "memanfaatkan fitur kuis yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur kuis e-learning?"
                        },
                        new
                        {
                            Id = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d"),
                            Advice = "memanfaatkan fitur konferensi video yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur konferensi video e-learning?"
                        },
                        new
                        {
                            Id = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e"),
                            Advice = "memberikan nilai tugas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil tugas"
                        },
                        new
                        {
                            Id = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c"),
                            Advice = "memberikan nilai kuis secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil kuis"
                        },
                        new
                        {
                            Id = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72"),
                            Advice = "memberikan nilai uts dan uas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil uts dan uas"
                        },
                        new
                        {
                            Id = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9"),
                            Advice = "hadir tepat waktu (maksimal 15 menit keterlambatan)",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah dosen hadir tepat waktu"
                        },
                        new
                        {
                            Id = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459"),
                            Advice = "memberikan perkuliahan sesuai dengan sesi yang sudah dialokasikan",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah perkuliahan dilaksanakan sesuai dengan alokasi waktu"
                        },
                        new
                        {
                            Id = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925"),
                            Advice = "menyampaikan materi sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah materi yang disampaikan sudah sesuai dengan rpp dan rps?"
                        },
                        new
                        {
                            Id = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552"),
                            Advice = "memberikan tugas sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah tugas yang diberikan sesuai dengan beban studi?"
                        },
                        new
                        {
                            Id = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de"),
                            Advice = "mencari referensi terkait materi yang diajarkan",
                            Section = "penguasaan materi",
                            Title = "Apakah dosen menguasai materi perkuliahan dengan baik?"
                        });
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AspectCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("SurveyId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f584b332-a830-2155-f34e-bc54009ca3ed"),
                            Email = "xanana@usu.ac.id",
                            Name = "Xanana",
                            Password = "xanana123"
                        },
                        new
                        {
                            Id = new Guid("ae28eb03-d5a0-cef0-fac4-dd78ce871f5b"),
                            Email = "cahyo@usu.ac.id",
                            Name = "Cahyo",
                            Password = "cahyo123"
                        },
                        new
                        {
                            Id = new Guid("5d3c03fa-d881-c80b-b7cb-b5b836712833"),
                            Email = "opan@usu.ac.id",
                            Name = "Opan",
                            Password = "opan123"
                        },
                        new
                        {
                            Id = new Guid("af1284ac-6105-90ad-437a-7f3535a44e5c"),
                            Email = "belinda@usu.ac.id",
                            Name = "Belinda",
                            Password = "belinda123"
                        },
                        new
                        {
                            Id = new Guid("4f69a578-d7a2-251e-1842-8e6b509b9d34"),
                            Email = "maras@usu.ac.id",
                            Name = "Maras",
                            Password = "maras123"
                        },
                        new
                        {
                            Id = new Guid("dbfe4b34-f0b0-9195-4982-961169d97f44"),
                            Email = "tami@usu.ac.id",
                            Name = "Tami",
                            Password = "tami123"
                        },
                        new
                        {
                            Id = new Guid("3be25c80-df90-6b48-02d7-29e49700f585"),
                            Email = "gandewa@usu.ac.id",
                            Name = "Gandewa",
                            Password = "gandewa123"
                        },
                        new
                        {
                            Id = new Guid("79f59ce5-11ba-9c8e-8f07-d8b5ec0cdf58"),
                            Email = "hesti@usu.ac.id",
                            Name = "Hesti",
                            Password = "hesti123"
                        },
                        new
                        {
                            Id = new Guid("1ebaf8e6-4492-bdee-6764-ea951be3b1d7"),
                            Email = "lukita@usu.ac.id",
                            Name = "Lukita",
                            Password = "lukita123"
                        },
                        new
                        {
                            Id = new Guid("d0a2074f-f4ad-4150-924c-eb1d043f4ca2"),
                            Email = "akarsana@usu.ac.id",
                            Name = "Akarsana",
                            Password = "akarsana123"
                        },
                        new
                        {
                            Id = new Guid("b00ac7ec-fc8a-29aa-b1f9-ebf50414aec1"),
                            Email = "daliman@usu.ac.id",
                            Name = "Daliman",
                            Password = "daliman123"
                        },
                        new
                        {
                            Id = new Guid("c54a15af-51ce-a1b2-d249-5fab49784481"),
                            Email = "rachel@usu.ac.id",
                            Name = "Rachel",
                            Password = "rachel123"
                        },
                        new
                        {
                            Id = new Guid("a57d9e13-8426-5643-559d-48d66f4336a0"),
                            Email = "jati@usu.ac.id",
                            Name = "Jati",
                            Password = "jati123"
                        },
                        new
                        {
                            Id = new Guid("b9f927e5-e8fe-602a-c906-b072b1822917"),
                            Email = "ikhsan@usu.ac.id",
                            Name = "Ikhsan",
                            Password = "ikhsan123"
                        },
                        new
                        {
                            Id = new Guid("c6ef092e-7782-14fb-59fb-da1b75a985ba"),
                            Email = "nova@usu.ac.id",
                            Name = "Nova",
                            Password = "nova123"
                        },
                        new
                        {
                            Id = new Guid("949f5a9d-c57b-3cba-a6e2-ecc5ac5796cb"),
                            Email = "perkasa@usu.ac.id",
                            Name = "Perkasa",
                            Password = "perkasa123"
                        },
                        new
                        {
                            Id = new Guid("81a51f99-e9bd-2e8f-86ae-9106edf6e766"),
                            Email = "radika@usu.ac.id",
                            Name = "Radika",
                            Password = "radika123"
                        },
                        new
                        {
                            Id = new Guid("2a8e9aca-450b-19d1-2893-4e8284a9379b"),
                            Email = "kiandra@usu.ac.id",
                            Name = "Kiandra",
                            Password = "kiandra123"
                        },
                        new
                        {
                            Id = new Guid("b59c1b1e-4c05-0c3e-ab9f-f4f5de46dd43"),
                            Email = "cawisadi@usu.ac.id",
                            Name = "Cawisadi",
                            Password = "cawisadi123"
                        },
                        new
                        {
                            Id = new Guid("5f136f5b-a4b0-fcc1-e004-29e7ce51d56a"),
                            Email = "cinta@usu.ac.id",
                            Name = "Cinta",
                            Password = "cinta123"
                        },
                        new
                        {
                            Id = new Guid("419414b6-ffeb-3199-2433-b408a440a860"),
                            Email = "gatra@usu.ac.id",
                            Name = "Gatra",
                            Password = "gatra123"
                        },
                        new
                        {
                            Id = new Guid("f76bbe69-08f4-396c-e2c3-d0a31f73fe7f"),
                            Email = "galur@usu.ac.id",
                            Name = "Galur",
                            Password = "galur123"
                        },
                        new
                        {
                            Id = new Guid("13831a42-7ec6-8d80-48d7-60e83f6e1124"),
                            Email = "gasti@usu.ac.id",
                            Name = "Gasti",
                            Password = "gasti123"
                        },
                        new
                        {
                            Id = new Guid("8c20bef2-b2d5-d51d-6181-13400924b3bb"),
                            Email = "abyasa@usu.ac.id",
                            Name = "Abyasa",
                            Password = "abyasa123"
                        },
                        new
                        {
                            Id = new Guid("ecf8552d-6677-94c0-d8fa-846291fb7275"),
                            Email = "ibun@usu.ac.id",
                            Name = "Ibun",
                            Password = "ibun123"
                        },
                        new
                        {
                            Id = new Guid("d145b6cc-f0f6-ff1d-7a07-ce3c34834feb"),
                            Email = "prima@usu.ac.id",
                            Name = "Prima",
                            Password = "prima123"
                        },
                        new
                        {
                            Id = new Guid("b9470590-40cb-23d9-51fe-ef17ce9396e5"),
                            Email = "farah@usu.ac.id",
                            Name = "Farah",
                            Password = "farah123"
                        },
                        new
                        {
                            Id = new Guid("085f5ce0-78cf-b8eb-c69c-c50013a505c6"),
                            Email = "maya@usu.ac.id",
                            Name = "Maya",
                            Password = "maya123"
                        },
                        new
                        {
                            Id = new Guid("04ea1286-d3f7-1f9e-0f63-393aa54f93e7"),
                            Email = "ami@usu.ac.id",
                            Name = "Ami",
                            Password = "ami123"
                        },
                        new
                        {
                            Id = new Guid("cf36884c-12cd-3d79-5d51-eb491207af0f"),
                            Email = "upik@usu.ac.id",
                            Name = "Upik",
                            Password = "upik123"
                        },
                        new
                        {
                            Id = new Guid("8c64dc7d-af69-8868-7e8c-f6756c2b9b6b"),
                            Email = "tasnim@usu.ac.id",
                            Name = "Tasnim",
                            Password = "tasnim123"
                        },
                        new
                        {
                            Id = new Guid("d845b750-ba8b-4c75-33c5-51328a96f1b7"),
                            Email = "rika@usu.ac.id",
                            Name = "Rika",
                            Password = "rika123"
                        },
                        new
                        {
                            Id = new Guid("861ebf35-4566-ed93-46e8-e5bfaea68d53"),
                            Email = "maimunah@usu.ac.id",
                            Name = "Maimunah",
                            Password = "maimunah123"
                        },
                        new
                        {
                            Id = new Guid("a950a597-1d17-a27b-374c-016083b5c16c"),
                            Email = "sadina@usu.ac.id",
                            Name = "Sadina",
                            Password = "sadina123"
                        },
                        new
                        {
                            Id = new Guid("0051c93d-9d44-8c73-6774-17aaa537d74b"),
                            Email = "karsa@usu.ac.id",
                            Name = "Karsa",
                            Password = "karsa123"
                        },
                        new
                        {
                            Id = new Guid("01a88bdd-c30a-470d-ece6-652ffd4170d2"),
                            Email = "kusuma@usu.ac.id",
                            Name = "Kusuma",
                            Password = "kusuma123"
                        },
                        new
                        {
                            Id = new Guid("b3609755-8a35-07b5-8b8c-a7c9883895fd"),
                            Email = "diah@usu.ac.id",
                            Name = "Diah",
                            Password = "diah123"
                        },
                        new
                        {
                            Id = new Guid("8dbf3b12-fdf2-8db1-2737-76d539d221e3"),
                            Email = "najwa@usu.ac.id",
                            Name = "Najwa",
                            Password = "najwa123"
                        },
                        new
                        {
                            Id = new Guid("1d552a63-034b-8138-9f22-5e2c9a00b3c6"),
                            Email = "ami@usu.ac.id",
                            Name = "Ami",
                            Password = "ami123"
                        },
                        new
                        {
                            Id = new Guid("63a5c835-a801-7e63-91b6-53d4a8a5420e"),
                            Email = "cinta@usu.ac.id",
                            Name = "Cinta",
                            Password = "cinta123"
                        },
                        new
                        {
                            Id = new Guid("bceff554-7055-8e5d-2ffa-9d7522721246"),
                            Email = "silvia@usu.ac.id",
                            Name = "Silvia",
                            Password = "silvia123"
                        },
                        new
                        {
                            Id = new Guid("ad28ffe1-cdb9-8271-2eca-7ab8ea8b674f"),
                            Email = "galuh@usu.ac.id",
                            Name = "Galuh",
                            Password = "galuh123"
                        },
                        new
                        {
                            Id = new Guid("347279eb-7205-6879-e01c-93e0c262f714"),
                            Email = "nasim@usu.ac.id",
                            Name = "Nasim",
                            Password = "nasim123"
                        },
                        new
                        {
                            Id = new Guid("213ba73b-d24a-9342-1476-10110ed30048"),
                            Email = "hendri@usu.ac.id",
                            Name = "Hendri",
                            Password = "hendri123"
                        },
                        new
                        {
                            Id = new Guid("b5faadba-5033-55ec-ee4d-0817c1d55fcd"),
                            Email = "wulan@usu.ac.id",
                            Name = "Wulan",
                            Password = "wulan123"
                        },
                        new
                        {
                            Id = new Guid("9f2ec98e-72f1-025e-58cf-0dc0e07907c3"),
                            Email = "ciaobella@usu.ac.id",
                            Name = "Ciaobella",
                            Password = "ciaobella123"
                        },
                        new
                        {
                            Id = new Guid("eb73859f-f534-f5e4-8bfc-b53bb241bf35"),
                            Email = "jaeman@usu.ac.id",
                            Name = "Jaeman",
                            Password = "jaeman123"
                        },
                        new
                        {
                            Id = new Guid("87bb1b05-3057-1df8-472d-6d8e0ffe7be0"),
                            Email = "jamalia@usu.ac.id",
                            Name = "Jamalia",
                            Password = "jamalia123"
                        },
                        new
                        {
                            Id = new Guid("3895a357-fcbb-61e7-4d1d-1ccc01aabf77"),
                            Email = "praba@usu.ac.id",
                            Name = "Praba",
                            Password = "praba123"
                        },
                        new
                        {
                            Id = new Guid("422d17c3-17f2-b6ae-87fc-edb7bfd21330"),
                            Email = "kanda@usu.ac.id",
                            Name = "Kanda",
                            Password = "kanda123"
                        },
                        new
                        {
                            Id = new Guid("be5fcdfb-f6a0-dbe3-017a-2cc2cf98403c"),
                            Email = "darmaji@usu.ac.id",
                            Name = "Darmaji",
                            Password = "darmaji123"
                        },
                        new
                        {
                            Id = new Guid("7eb01460-048a-ea75-7496-5d49b9d0cca8"),
                            Email = "banara@usu.ac.id",
                            Name = "Banara",
                            Password = "banara123"
                        },
                        new
                        {
                            Id = new Guid("377605df-165f-3315-8ac4-2d547682b6fd"),
                            Email = "najam@usu.ac.id",
                            Name = "Najam",
                            Password = "najam123"
                        },
                        new
                        {
                            Id = new Guid("5a427d65-b649-4d82-7db7-c15bf6261c50"),
                            Email = "zelaya@usu.ac.id",
                            Name = "Zelaya",
                            Password = "zelaya123"
                        },
                        new
                        {
                            Id = new Guid("99b5289f-5668-b07a-bd1f-1fda93bc0002"),
                            Email = "olga@usu.ac.id",
                            Name = "Olga",
                            Password = "olga123"
                        },
                        new
                        {
                            Id = new Guid("c0bc84ad-11b5-5d99-722e-ce063825259f"),
                            Email = "maria@usu.ac.id",
                            Name = "Maria",
                            Password = "maria123"
                        },
                        new
                        {
                            Id = new Guid("ec14cb14-98e0-62f8-2da3-24045bf3e21d"),
                            Email = "estiono@usu.ac.id",
                            Name = "Estiono",
                            Password = "estiono123"
                        },
                        new
                        {
                            Id = new Guid("a373de5a-0a00-4be3-e2b6-e7f9b5f45e58"),
                            Email = "pangestu@usu.ac.id",
                            Name = "Pangestu",
                            Password = "pangestu123"
                        },
                        new
                        {
                            Id = new Guid("23a3c1e9-53c8-f5e4-396e-d3da241a824b"),
                            Email = "rika@usu.ac.id",
                            Name = "Rika",
                            Password = "rika123"
                        },
                        new
                        {
                            Id = new Guid("0aca7134-9508-41b5-7a33-ed30a502056b"),
                            Email = "dewi@usu.ac.id",
                            Name = "Dewi",
                            Password = "dewi123"
                        },
                        new
                        {
                            Id = new Guid("20163635-0bbf-75d0-7808-92cd7769afe0"),
                            Email = "yuni@usu.ac.id",
                            Name = "Yuni",
                            Password = "yuni123"
                        },
                        new
                        {
                            Id = new Guid("0eb8dfad-866e-b0d8-0809-c8d0d4b9e6a0"),
                            Email = "lukita@usu.ac.id",
                            Name = "Lukita",
                            Password = "lukita123"
                        },
                        new
                        {
                            Id = new Guid("bfb21467-9339-ad1c-afad-bc8380c5de88"),
                            Email = "laila@usu.ac.id",
                            Name = "Laila",
                            Password = "laila123"
                        },
                        new
                        {
                            Id = new Guid("90c82629-0e47-c702-ada8-33d9e6d653a1"),
                            Email = "hari@usu.ac.id",
                            Name = "Hari",
                            Password = "hari123"
                        },
                        new
                        {
                            Id = new Guid("25a5edca-c1f2-2ad6-f384-8802f14cfb92"),
                            Email = "jessica@usu.ac.id",
                            Name = "Jessica",
                            Password = "jessica123"
                        },
                        new
                        {
                            Id = new Guid("a3ccd745-72bc-74e6-79d6-c7e530de4dcd"),
                            Email = "hafshah@usu.ac.id",
                            Name = "Hafshah",
                            Password = "hafshah123"
                        },
                        new
                        {
                            Id = new Guid("073404ae-1db9-7e1b-3eaa-b6e7de546064"),
                            Email = "nadia@usu.ac.id",
                            Name = "Nadia",
                            Password = "nadia123"
                        },
                        new
                        {
                            Id = new Guid("33302744-7d3e-0047-630d-54aab5238e2a"),
                            Email = "cawisono@usu.ac.id",
                            Name = "Cawisono",
                            Password = "cawisono123"
                        },
                        new
                        {
                            Id = new Guid("af1e3dba-3e87-3b34-bd92-f77385cc81ad"),
                            Email = "betania@usu.ac.id",
                            Name = "Betania",
                            Password = "betania123"
                        },
                        new
                        {
                            Id = new Guid("b7c57b9f-b8c0-0db9-2a93-f59259b370ee"),
                            Email = "gadang@usu.ac.id",
                            Name = "Gadang",
                            Password = "gadang123"
                        },
                        new
                        {
                            Id = new Guid("f29f9482-02fe-b5bf-09f0-8887280899f8"),
                            Email = "padma@usu.ac.id",
                            Name = "Padma",
                            Password = "padma123"
                        },
                        new
                        {
                            Id = new Guid("657d03ac-7af5-a013-462b-394402972262"),
                            Email = "fitria@usu.ac.id",
                            Name = "Fitria",
                            Password = "fitria123"
                        },
                        new
                        {
                            Id = new Guid("c27cacf6-0af7-c9af-84a2-6bedf8602709"),
                            Email = "yulia@usu.ac.id",
                            Name = "Yulia",
                            Password = "yulia123"
                        },
                        new
                        {
                            Id = new Guid("259f1ca1-5ede-94bc-7cc4-eef064c6dda4"),
                            Email = "anastasia@usu.ac.id",
                            Name = "Anastasia",
                            Password = "anastasia123"
                        },
                        new
                        {
                            Id = new Guid("720ce9ea-2cb6-71f5-3559-32d81df8567c"),
                            Email = "carla@usu.ac.id",
                            Name = "Carla",
                            Password = "carla123"
                        },
                        new
                        {
                            Id = new Guid("1ecdd156-6206-eb8e-db94-3da40f535e48"),
                            Email = "sakura@usu.ac.id",
                            Name = "Sakura",
                            Password = "sakura123"
                        },
                        new
                        {
                            Id = new Guid("72662e99-6d2f-6228-61a3-a7f59ae805cf"),
                            Email = "paulin@usu.ac.id",
                            Name = "Paulin",
                            Password = "paulin123"
                        },
                        new
                        {
                            Id = new Guid("a9e3cc11-cbe4-6150-3390-49de79d4dafe"),
                            Email = "leo@usu.ac.id",
                            Name = "Leo",
                            Password = "leo123"
                        },
                        new
                        {
                            Id = new Guid("5fa2e3a7-a3f5-ea00-44e6-f9559f40052e"),
                            Email = "liman@usu.ac.id",
                            Name = "Liman",
                            Password = "liman123"
                        },
                        new
                        {
                            Id = new Guid("9b4af074-cd22-983a-1883-2ad21a9c0474"),
                            Email = "dodo@usu.ac.id",
                            Name = "Dodo",
                            Password = "dodo123"
                        },
                        new
                        {
                            Id = new Guid("3fd6b18e-f9a8-6a87-68dd-f109d94b9d87"),
                            Email = "dinda@usu.ac.id",
                            Name = "Dinda",
                            Password = "dinda123"
                        },
                        new
                        {
                            Id = new Guid("d4c10c46-5d25-7d8b-c071-cb5c502b199a"),
                            Email = "hani@usu.ac.id",
                            Name = "Hani",
                            Password = "hani123"
                        },
                        new
                        {
                            Id = new Guid("5147357c-b714-5c64-a70f-a9df34931211"),
                            Email = "luwar@usu.ac.id",
                            Name = "Luwar",
                            Password = "luwar123"
                        },
                        new
                        {
                            Id = new Guid("798cbaaa-2ab4-1539-9f0c-8dc6f03fab18"),
                            Email = "jagaraga@usu.ac.id",
                            Name = "Jagaraga",
                            Password = "jagaraga123"
                        },
                        new
                        {
                            Id = new Guid("09f8f5ab-c96f-7bb6-d4e0-3c37493efdfe"),
                            Email = "limar@usu.ac.id",
                            Name = "Limar",
                            Password = "limar123"
                        },
                        new
                        {
                            Id = new Guid("1c8002f9-fe17-5818-cfe0-1f6a341c88be"),
                            Email = "jarwa@usu.ac.id",
                            Name = "Jarwa",
                            Password = "jarwa123"
                        },
                        new
                        {
                            Id = new Guid("c34aa021-38c3-5956-d867-c24ec8f14fc5"),
                            Email = "hasan@usu.ac.id",
                            Name = "Hasan",
                            Password = "hasan123"
                        },
                        new
                        {
                            Id = new Guid("fade8ed3-16f1-d5fa-5c69-ac20af8bd8c6"),
                            Email = "kezia@usu.ac.id",
                            Name = "Kezia",
                            Password = "kezia123"
                        },
                        new
                        {
                            Id = new Guid("483f359b-bec6-b125-9680-182d1b6efd7f"),
                            Email = "kamila@usu.ac.id",
                            Name = "Kamila",
                            Password = "kamila123"
                        },
                        new
                        {
                            Id = new Guid("33af2759-edc8-ecdc-acb8-b737750215ff"),
                            Email = "genta@usu.ac.id",
                            Name = "Genta",
                            Password = "genta123"
                        },
                        new
                        {
                            Id = new Guid("1fc78bc8-40d4-7980-bd2f-4e3d2230a001"),
                            Email = "yance@usu.ac.id",
                            Name = "Yance",
                            Password = "yance123"
                        },
                        new
                        {
                            Id = new Guid("516d67a0-da6c-6c11-f95f-0b16171b4314"),
                            Email = "nurul@usu.ac.id",
                            Name = "Nurul",
                            Password = "nurul123"
                        },
                        new
                        {
                            Id = new Guid("6f52390f-4fb3-ac30-9d6f-968796739560"),
                            Email = "ami@usu.ac.id",
                            Name = "Ami",
                            Password = "ami123"
                        },
                        new
                        {
                            Id = new Guid("ed1f767c-670e-2146-6da6-1733f90e7940"),
                            Email = "elma@usu.ac.id",
                            Name = "Elma",
                            Password = "elma123"
                        },
                        new
                        {
                            Id = new Guid("1db43062-bf21-a23d-d672-c89781b7bb80"),
                            Email = "elma@usu.ac.id",
                            Name = "Elma",
                            Password = "elma123"
                        },
                        new
                        {
                            Id = new Guid("ea2b2240-9228-8ae1-9569-75870d568161"),
                            Email = "bakianto@usu.ac.id",
                            Name = "Bakianto",
                            Password = "bakianto123"
                        },
                        new
                        {
                            Id = new Guid("60555e0e-6baf-d491-58d6-256077787639"),
                            Email = "rini@usu.ac.id",
                            Name = "Rini",
                            Password = "rini123"
                        },
                        new
                        {
                            Id = new Guid("41cdc211-9ad2-44df-9ad0-122014cd918b"),
                            Email = "admin@usu.ac.id",
                            Name = "Admin",
                            Password = "admin123"
                        },
                        new
                        {
                            Id = new Guid("107e9536-5fd4-4b44-891e-9e77eb5ca9ab"),
                            Email = "alvin@usu.ac.id",
                            Name = "Alvin",
                            Password = "alvin123"
                        },
                        new
                        {
                            Id = new Guid("6e8173db-65aa-4b55-b030-eee00927cd39"),
                            Email = "febriando@usu.ac.id",
                            Name = "Febriando",
                            Password = "febriando123"
                        });
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.Property<Guid>("AnsweredById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveysId")
                        .HasColumnType("uuid");

                    b.HasKey("AnsweredById", "SurveysId");

                    b.HasIndex("SurveysId");

                    b.ToTable("SurveyUser");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.SurveyQuestion", "SurveyQuestion")
                        .WithMany()
                        .HasForeignKey("SurveyQuestionSurveyId", "SurveyQuestionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", "Survey")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AnsweredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Navigation("SurveyQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
