// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Questionnaire.Infrastructure.Persistence.Postgres;

#nullable disable

namespace Questionnaire.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230530035846_SeedUserTable")]
    partial class SeedUserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SurveyQuestionQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveyQuestionSurveyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionSurveyId", "SurveyQuestionQuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e"),
                            Advice = "memberikan kesempatan bertanya di dalam kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di dalam kelas?"
                        },
                        new
                        {
                            Id = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9"),
                            Advice = "memberikan kesempatan bertanya di luar kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di luar kelas?"
                        },
                        new
                        {
                            Id = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803"),
                            Advice = "memanfaatkan fitur forum yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur forum e-learning?"
                        },
                        new
                        {
                            Id = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f"),
                            Advice = "memanfaatkan fitur kuis yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur kuis e-learning?"
                        },
                        new
                        {
                            Id = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d"),
                            Advice = "memanfaatkan fitur konferensi video yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur konferensi video e-learning?"
                        },
                        new
                        {
                            Id = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e"),
                            Advice = "memberikan nilai tugas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil tugas"
                        },
                        new
                        {
                            Id = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c"),
                            Advice = "memberikan nilai kuis secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil kuis"
                        },
                        new
                        {
                            Id = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72"),
                            Advice = "memberikan nilai uts dan uas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil uts dan uas"
                        },
                        new
                        {
                            Id = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9"),
                            Advice = "hadir tepat waktu (maksimal 15 menit keterlambatan)",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah dosen hadir tepat waktu"
                        },
                        new
                        {
                            Id = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459"),
                            Advice = "memberikan perkuliahan sesuai dengan sesi yang sudah dialokasikan",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah perkuliahan dilaksanakan sesuai dengan alokasi waktu"
                        },
                        new
                        {
                            Id = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925"),
                            Advice = "menyampaikan materi sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah materi yang disampaikan sudah sesuai dengan rpp dan rps?"
                        },
                        new
                        {
                            Id = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552"),
                            Advice = "memberikan tugas sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah tugas yang diberikan sesuai dengan beban studi?"
                        },
                        new
                        {
                            Id = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de"),
                            Advice = "mencari referensi terkait materi yang diajarkan",
                            Section = "penguasaan materi",
                            Title = "Apakah dosen menguasai materi perkuliahan dengan baik?"
                        });
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AspectCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("SurveyId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ccf4bae-bf21-e005-26f2-a6d43d8d1d18"),
                            Email = "karen@usu.ac.id",
                            Name = "Karen",
                            Password = "Karen123"
                        },
                        new
                        {
                            Id = new Guid("451f43fc-e9c0-df41-5f85-c64ada710867"),
                            Email = "kartika@usu.ac.id",
                            Name = "Kartika",
                            Password = "Kartika123"
                        },
                        new
                        {
                            Id = new Guid("5cd39ed8-59cf-fa2f-1bb2-e83efc0e0fd9"),
                            Email = "intan@usu.ac.id",
                            Name = "Intan",
                            Password = "Intan123"
                        },
                        new
                        {
                            Id = new Guid("5004b5f7-cd5c-d6c2-6861-78991759ff7e"),
                            Email = "jarwi@usu.ac.id",
                            Name = "Jarwi",
                            Password = "Jarwi123"
                        },
                        new
                        {
                            Id = new Guid("b914cb35-f88b-f124-0db4-c4f8c02b5767"),
                            Email = "vero@usu.ac.id",
                            Name = "Vero",
                            Password = "Vero123"
                        },
                        new
                        {
                            Id = new Guid("f27754ca-0285-058e-9869-c4a2e2ca90a5"),
                            Email = "kariman@usu.ac.id",
                            Name = "Kariman",
                            Password = "Kariman123"
                        },
                        new
                        {
                            Id = new Guid("d79cd39a-85d1-9fa4-b50a-02a09c40c820"),
                            Email = "rachel@usu.ac.id",
                            Name = "Rachel",
                            Password = "Rachel123"
                        },
                        new
                        {
                            Id = new Guid("185ecf52-22af-a044-9499-c5904344d102"),
                            Email = "chelsea@usu.ac.id",
                            Name = "Chelsea",
                            Password = "Chelsea123"
                        },
                        new
                        {
                            Id = new Guid("f56cbb1f-ae0a-afff-a390-d79bc421127b"),
                            Email = "iriana@usu.ac.id",
                            Name = "Iriana",
                            Password = "Iriana123"
                        },
                        new
                        {
                            Id = new Guid("42107ffc-4a6f-aab5-f0d7-7f9ccd956ea1"),
                            Email = "umaya@usu.ac.id",
                            Name = "Umaya",
                            Password = "Umaya123"
                        },
                        new
                        {
                            Id = new Guid("c66b72da-0e4e-e67e-f328-1c4cb62b9c90"),
                            Email = "dian@usu.ac.id",
                            Name = "Dian",
                            Password = "Dian123"
                        },
                        new
                        {
                            Id = new Guid("f3cce24f-09b2-d5d6-1ff9-c6f36c80e20f"),
                            Email = "mariadi@usu.ac.id",
                            Name = "Mariadi",
                            Password = "Mariadi123"
                        },
                        new
                        {
                            Id = new Guid("662bdaad-44e8-06d7-9136-ba5c54aa85bb"),
                            Email = "icha@usu.ac.id",
                            Name = "Icha",
                            Password = "Icha123"
                        },
                        new
                        {
                            Id = new Guid("a6607bbc-49cd-8c4e-177a-c5598e35d868"),
                            Email = "yessi@usu.ac.id",
                            Name = "Yessi",
                            Password = "Yessi123"
                        },
                        new
                        {
                            Id = new Guid("4479079d-a2fe-ebaf-d013-6a77dc16b6fb"),
                            Email = "gaiman@usu.ac.id",
                            Name = "Gaiman",
                            Password = "Gaiman123"
                        },
                        new
                        {
                            Id = new Guid("48f5df0c-1a73-3238-29ca-e05b76b98aa4"),
                            Email = "rika@usu.ac.id",
                            Name = "Rika",
                            Password = "Rika123"
                        },
                        new
                        {
                            Id = new Guid("a6107d2e-e5e3-66ba-39af-55fb4fcd4089"),
                            Email = "cengkal@usu.ac.id",
                            Name = "Cengkal",
                            Password = "Cengkal123"
                        },
                        new
                        {
                            Id = new Guid("abd49037-0e54-78d1-53b9-136c133cc845"),
                            Email = "devi@usu.ac.id",
                            Name = "Devi",
                            Password = "Devi123"
                        },
                        new
                        {
                            Id = new Guid("2710c8ad-df53-1c85-4c82-3ab18780f909"),
                            Email = "mursinin@usu.ac.id",
                            Name = "Mursinin",
                            Password = "Mursinin123"
                        },
                        new
                        {
                            Id = new Guid("0b729f48-b326-1a3c-7ea1-af1aa699e089"),
                            Email = "lamar@usu.ac.id",
                            Name = "Lamar",
                            Password = "Lamar123"
                        },
                        new
                        {
                            Id = new Guid("43cf7007-09ea-66a5-9db6-4675378b0043"),
                            Email = "kania@usu.ac.id",
                            Name = "Kania",
                            Password = "Kania123"
                        },
                        new
                        {
                            Id = new Guid("3df9e2a4-18a3-2db4-0f27-ed75d1d61a46"),
                            Email = "ilsa@usu.ac.id",
                            Name = "Ilsa",
                            Password = "Ilsa123"
                        },
                        new
                        {
                            Id = new Guid("0e771438-2c5a-fcfa-a7b5-b484c8b27a14"),
                            Email = "sakura@usu.ac.id",
                            Name = "Sakura",
                            Password = "Sakura123"
                        },
                        new
                        {
                            Id = new Guid("0233d0cb-e6c1-40f8-fbbe-24a0e751be30"),
                            Email = "nadine@usu.ac.id",
                            Name = "Nadine",
                            Password = "Nadine123"
                        },
                        new
                        {
                            Id = new Guid("aee8ec9c-a61b-7dec-f0b6-e365097066db"),
                            Email = "endah@usu.ac.id",
                            Name = "Endah",
                            Password = "Endah123"
                        },
                        new
                        {
                            Id = new Guid("f937fb1d-3bb1-b614-2230-769861f00dd3"),
                            Email = "cahyanto@usu.ac.id",
                            Name = "Cahyanto",
                            Password = "Cahyanto123"
                        },
                        new
                        {
                            Id = new Guid("e6ad19b9-448a-5f42-ec01-b0f5fd3af852"),
                            Email = "zelda@usu.ac.id",
                            Name = "Zelda",
                            Password = "Zelda123"
                        },
                        new
                        {
                            Id = new Guid("48fdfa65-b864-42f0-6fbb-3daf5fc70f75"),
                            Email = "kania@usu.ac.id",
                            Name = "Kania",
                            Password = "Kania123"
                        },
                        new
                        {
                            Id = new Guid("1f494856-7f67-ea33-a127-dd8b0d3fe278"),
                            Email = "putri@usu.ac.id",
                            Name = "Putri",
                            Password = "Putri123"
                        },
                        new
                        {
                            Id = new Guid("68d5a9a6-3a04-3944-5c03-8716164767d1"),
                            Email = "jayeng@usu.ac.id",
                            Name = "Jayeng",
                            Password = "Jayeng123"
                        },
                        new
                        {
                            Id = new Guid("4a07686b-a855-d006-51f1-50fca0ca3676"),
                            Email = "luwar@usu.ac.id",
                            Name = "Luwar",
                            Password = "Luwar123"
                        },
                        new
                        {
                            Id = new Guid("5541c04b-1523-375f-bc1a-976fff90a341"),
                            Email = "zulaikha@usu.ac.id",
                            Name = "Zulaikha",
                            Password = "Zulaikha123"
                        },
                        new
                        {
                            Id = new Guid("4dc33bd7-0e6b-55b3-72bf-880674f8cd68"),
                            Email = "silvia@usu.ac.id",
                            Name = "Silvia",
                            Password = "Silvia123"
                        },
                        new
                        {
                            Id = new Guid("6bf81299-b2f9-eba0-74cc-57c89ba25274"),
                            Email = "pangestu@usu.ac.id",
                            Name = "Pangestu",
                            Password = "Pangestu123"
                        },
                        new
                        {
                            Id = new Guid("bc5f5228-51d9-8344-3efe-13335560a61d"),
                            Email = "oliva@usu.ac.id",
                            Name = "Oliva",
                            Password = "Oliva123"
                        },
                        new
                        {
                            Id = new Guid("e0c02164-779b-a32e-08ea-02e26ae64b4d"),
                            Email = "dimaz@usu.ac.id",
                            Name = "Dimaz",
                            Password = "Dimaz123"
                        },
                        new
                        {
                            Id = new Guid("b2ef4200-e9ab-d74d-ab78-6ce8ef9164a8"),
                            Email = "safina@usu.ac.id",
                            Name = "Safina",
                            Password = "Safina123"
                        },
                        new
                        {
                            Id = new Guid("28fe19b3-31bf-7e19-e7b8-83c80c447106"),
                            Email = "gatra@usu.ac.id",
                            Name = "Gatra",
                            Password = "Gatra123"
                        },
                        new
                        {
                            Id = new Guid("3277c706-e634-06b7-a46f-7a6a636800c9"),
                            Email = "salsabila@usu.ac.id",
                            Name = "Salsabila",
                            Password = "Salsabila123"
                        },
                        new
                        {
                            Id = new Guid("575f5d61-4a1d-6ea9-6ea1-c1113aa9aeab"),
                            Email = "samiah@usu.ac.id",
                            Name = "Samiah",
                            Password = "Samiah123"
                        },
                        new
                        {
                            Id = new Guid("7da018cc-defa-11a9-b8d1-521f3f0805e0"),
                            Email = "virman@usu.ac.id",
                            Name = "Virman",
                            Password = "Virman123"
                        },
                        new
                        {
                            Id = new Guid("04e8a387-05b1-d2f0-a193-55c5a62ebbeb"),
                            Email = "kunthara@usu.ac.id",
                            Name = "Kunthara",
                            Password = "Kunthara123"
                        },
                        new
                        {
                            Id = new Guid("529482dc-72e6-89ca-06e9-74cf8a913fea"),
                            Email = "dono@usu.ac.id",
                            Name = "Dono",
                            Password = "Dono123"
                        },
                        new
                        {
                            Id = new Guid("9330956d-b3f4-0c52-dc4a-ba01e3abf371"),
                            Email = "mumpuni@usu.ac.id",
                            Name = "Mumpuni",
                            Password = "Mumpuni123"
                        },
                        new
                        {
                            Id = new Guid("7a9de7a1-fac1-9b14-308b-d6342f5a5066"),
                            Email = "amalia@usu.ac.id",
                            Name = "Amalia",
                            Password = "Amalia123"
                        },
                        new
                        {
                            Id = new Guid("e78a1fd9-dab0-1d95-8597-8e8f762067d7"),
                            Email = "lala@usu.ac.id",
                            Name = "Lala",
                            Password = "Lala123"
                        },
                        new
                        {
                            Id = new Guid("c37cbe52-17da-479f-767c-0c6afee7d8c5"),
                            Email = "danu@usu.ac.id",
                            Name = "Danu",
                            Password = "Danu123"
                        },
                        new
                        {
                            Id = new Guid("3b876965-1bb0-b077-edf3-02f91775b6c2"),
                            Email = "vega@usu.ac.id",
                            Name = "Vega",
                            Password = "Vega123"
                        },
                        new
                        {
                            Id = new Guid("eb216f36-1149-a75d-ee07-6e44abc25e49"),
                            Email = "hilda@usu.ac.id",
                            Name = "Hilda",
                            Password = "Hilda123"
                        },
                        new
                        {
                            Id = new Guid("dc1d9c67-0c04-b9b6-8320-218c202f4e49"),
                            Email = "kacung@usu.ac.id",
                            Name = "Kacung",
                            Password = "Kacung123"
                        },
                        new
                        {
                            Id = new Guid("a9b04f09-4487-1fd7-d7c2-8efde3db1f0a"),
                            Email = "nyoman@usu.ac.id",
                            Name = "Nyoman",
                            Password = "Nyoman123"
                        },
                        new
                        {
                            Id = new Guid("b57353d8-73b3-4824-2e90-3dcc5d2fd777"),
                            Email = "ifa@usu.ac.id",
                            Name = "Ifa",
                            Password = "Ifa123"
                        },
                        new
                        {
                            Id = new Guid("5c5c531e-a5c2-dde7-583e-bfca65b59879"),
                            Email = "galak@usu.ac.id",
                            Name = "Galak",
                            Password = "Galak123"
                        },
                        new
                        {
                            Id = new Guid("5bcc6a0c-7e62-5269-e865-200234d92f9d"),
                            Email = "gandewa@usu.ac.id",
                            Name = "Gandewa",
                            Password = "Gandewa123"
                        },
                        new
                        {
                            Id = new Guid("b5b28ba3-f0f0-4047-9991-fdfc10dfd1c5"),
                            Email = "dariati@usu.ac.id",
                            Name = "Dariati",
                            Password = "Dariati123"
                        },
                        new
                        {
                            Id = new Guid("f655cf17-07b8-7cad-cf67-07fd89ef3572"),
                            Email = "harjasa@usu.ac.id",
                            Name = "Harjasa",
                            Password = "Harjasa123"
                        },
                        new
                        {
                            Id = new Guid("bd0d688b-5818-98d7-5e15-5cedd25afb89"),
                            Email = "martani@usu.ac.id",
                            Name = "Martani",
                            Password = "Martani123"
                        },
                        new
                        {
                            Id = new Guid("b76cfa8c-a998-5af5-ffea-28704f03d11d"),
                            Email = "puji@usu.ac.id",
                            Name = "Puji",
                            Password = "Puji123"
                        },
                        new
                        {
                            Id = new Guid("a223cc2f-af4e-ba35-5749-f798764d8301"),
                            Email = "wardaya@usu.ac.id",
                            Name = "Wardaya",
                            Password = "Wardaya123"
                        },
                        new
                        {
                            Id = new Guid("f245b8a8-3380-504d-86ff-ad9d12df2636"),
                            Email = "luwes@usu.ac.id",
                            Name = "Luwes",
                            Password = "Luwes123"
                        },
                        new
                        {
                            Id = new Guid("b71709aa-ef4a-02de-81a9-47d806005178"),
                            Email = "karsa@usu.ac.id",
                            Name = "Karsa",
                            Password = "Karsa123"
                        },
                        new
                        {
                            Id = new Guid("14274cc5-1c33-7d91-d7af-064f93d90b16"),
                            Email = "calista@usu.ac.id",
                            Name = "Calista",
                            Password = "Calista123"
                        },
                        new
                        {
                            Id = new Guid("edb958df-76f7-5bca-04bd-121718287273"),
                            Email = "winda@usu.ac.id",
                            Name = "Winda",
                            Password = "Winda123"
                        },
                        new
                        {
                            Id = new Guid("2d9b05e8-ae1d-953a-be29-0ababff63e79"),
                            Email = "lasmono@usu.ac.id",
                            Name = "Lasmono",
                            Password = "Lasmono123"
                        },
                        new
                        {
                            Id = new Guid("a610fd3f-f6aa-0b95-eb8f-a46a55f16da7"),
                            Email = "kemal@usu.ac.id",
                            Name = "Kemal",
                            Password = "Kemal123"
                        },
                        new
                        {
                            Id = new Guid("a02f155c-28aa-1238-8e4c-dbb29e04500e"),
                            Email = "cawisono@usu.ac.id",
                            Name = "Cawisono",
                            Password = "Cawisono123"
                        },
                        new
                        {
                            Id = new Guid("ac8297e6-050e-88ee-904b-ab82ea56c22e"),
                            Email = "kambali@usu.ac.id",
                            Name = "Kambali",
                            Password = "Kambali123"
                        },
                        new
                        {
                            Id = new Guid("83c747ea-9fb9-bcc5-115b-565ae0b32ba6"),
                            Email = "oman@usu.ac.id",
                            Name = "Oman",
                            Password = "Oman123"
                        },
                        new
                        {
                            Id = new Guid("ef3f89b1-8047-c57e-3052-a19bf8080117"),
                            Email = "luwes@usu.ac.id",
                            Name = "Luwes",
                            Password = "Luwes123"
                        },
                        new
                        {
                            Id = new Guid("f2d09c3b-192b-01dc-1cb4-561eca6f38c5"),
                            Email = "kartika@usu.ac.id",
                            Name = "Kartika",
                            Password = "Kartika123"
                        },
                        new
                        {
                            Id = new Guid("61bf8128-5330-4fcf-6c06-83e67bc27f07"),
                            Email = "lukita@usu.ac.id",
                            Name = "Lukita",
                            Password = "Lukita123"
                        },
                        new
                        {
                            Id = new Guid("4f63d9cb-153e-0e59-51fa-f9ade81a75ae"),
                            Email = "zamira@usu.ac.id",
                            Name = "Zamira",
                            Password = "Zamira123"
                        },
                        new
                        {
                            Id = new Guid("f2ca4148-ec41-20f7-8a02-9d6b0af3dd5d"),
                            Email = "aurora@usu.ac.id",
                            Name = "Aurora",
                            Password = "Aurora123"
                        },
                        new
                        {
                            Id = new Guid("ef7652f7-d719-c8fe-a4fb-ad162c52911d"),
                            Email = "arsipatra@usu.ac.id",
                            Name = "Arsipatra",
                            Password = "Arsipatra123"
                        },
                        new
                        {
                            Id = new Guid("750b55e4-7bd5-41dc-feef-f9aa3fdc5ae6"),
                            Email = "harto@usu.ac.id",
                            Name = "Harto",
                            Password = "Harto123"
                        },
                        new
                        {
                            Id = new Guid("924f8a26-c8b7-d26a-68a6-4eba354ce82d"),
                            Email = "lega@usu.ac.id",
                            Name = "Lega",
                            Password = "Lega123"
                        },
                        new
                        {
                            Id = new Guid("ab20c6a0-a67c-a441-9ad9-fd63f939e9dc"),
                            Email = "cahyo@usu.ac.id",
                            Name = "Cahyo",
                            Password = "Cahyo123"
                        },
                        new
                        {
                            Id = new Guid("318eb719-2d8c-2d06-481d-43e271aaa733"),
                            Email = "danu@usu.ac.id",
                            Name = "Danu",
                            Password = "Danu123"
                        },
                        new
                        {
                            Id = new Guid("a2fc7cf0-0479-6ae8-409d-fef884e2e454"),
                            Email = "galur@usu.ac.id",
                            Name = "Galur",
                            Password = "Galur123"
                        },
                        new
                        {
                            Id = new Guid("2dc1d6f4-2b40-0ceb-671c-424268254502"),
                            Email = "yuliana@usu.ac.id",
                            Name = "Yuliana",
                            Password = "Yuliana123"
                        },
                        new
                        {
                            Id = new Guid("f49a3428-ebbc-835a-60cd-6f20304b706a"),
                            Email = "garda@usu.ac.id",
                            Name = "Garda",
                            Password = "Garda123"
                        },
                        new
                        {
                            Id = new Guid("9f3e9bf6-c2b4-8181-f324-a156cee909e9"),
                            Email = "kani@usu.ac.id",
                            Name = "Kani",
                            Password = "Kani123"
                        },
                        new
                        {
                            Id = new Guid("6dc9a8ae-72af-ad97-1a19-d5b7ea7bad34"),
                            Email = "keisha@usu.ac.id",
                            Name = "Keisha",
                            Password = "Keisha123"
                        },
                        new
                        {
                            Id = new Guid("ba78cc46-89b3-a099-928e-eb54747f435d"),
                            Email = "unjani@usu.ac.id",
                            Name = "Unjani",
                            Password = "Unjani123"
                        },
                        new
                        {
                            Id = new Guid("97eda8b9-4856-2562-a1eb-f5e71629ccdf"),
                            Email = "ismail@usu.ac.id",
                            Name = "Ismail",
                            Password = "Ismail123"
                        },
                        new
                        {
                            Id = new Guid("b0851aa5-8d9d-4288-60d0-8f3c86d768e9"),
                            Email = "heryanto@usu.ac.id",
                            Name = "Heryanto",
                            Password = "Heryanto123"
                        },
                        new
                        {
                            Id = new Guid("59f8734d-5a44-9ded-0514-20b8d6a3e5bc"),
                            Email = "harimurti@usu.ac.id",
                            Name = "Harimurti",
                            Password = "Harimurti123"
                        },
                        new
                        {
                            Id = new Guid("5ca56578-2ffe-229a-4d24-4538ed5f0f02"),
                            Email = "melinda@usu.ac.id",
                            Name = "Melinda",
                            Password = "Melinda123"
                        },
                        new
                        {
                            Id = new Guid("7d43c2e3-38ec-7ab1-489d-dff20a53a47c"),
                            Email = "surya@usu.ac.id",
                            Name = "Surya",
                            Password = "Surya123"
                        },
                        new
                        {
                            Id = new Guid("5ee9e1c6-d05f-0674-f99d-01d2763221bc"),
                            Email = "taswir@usu.ac.id",
                            Name = "Taswir",
                            Password = "Taswir123"
                        },
                        new
                        {
                            Id = new Guid("5559eac3-9934-daab-e948-ae62a57e72a4"),
                            Email = "ade@usu.ac.id",
                            Name = "Ade",
                            Password = "Ade123"
                        },
                        new
                        {
                            Id = new Guid("9624ac54-ca9b-48ce-6279-2f2c49377293"),
                            Email = "karman@usu.ac.id",
                            Name = "Karman",
                            Password = "Karman123"
                        },
                        new
                        {
                            Id = new Guid("4783528f-bf73-6d7f-a09a-70a7eee65f02"),
                            Email = "rusman@usu.ac.id",
                            Name = "Rusman",
                            Password = "Rusman123"
                        },
                        new
                        {
                            Id = new Guid("82f203ef-66d1-f503-207d-d922efddcfc2"),
                            Email = "lanang@usu.ac.id",
                            Name = "Lanang",
                            Password = "Lanang123"
                        },
                        new
                        {
                            Id = new Guid("f2898a40-0a3f-4bdf-ce3f-1893cf9f27d6"),
                            Email = "cakrajiya@usu.ac.id",
                            Name = "Cakrajiya",
                            Password = "Cakrajiya123"
                        },
                        new
                        {
                            Id = new Guid("18492ab7-fe7d-0520-8354-943bcd98b839"),
                            Email = "hamzah@usu.ac.id",
                            Name = "Hamzah",
                            Password = "Hamzah123"
                        },
                        new
                        {
                            Id = new Guid("f08966a8-18fb-215a-1d54-97abfd060db5"),
                            Email = "kusuma@usu.ac.id",
                            Name = "Kusuma",
                            Password = "Kusuma123"
                        },
                        new
                        {
                            Id = new Guid("41cdc211-9ad2-44df-9ad0-122014cd918b"),
                            Email = "admin@usu.ac.id",
                            Name = "Admin",
                            Password = "admin123"
                        },
                        new
                        {
                            Id = new Guid("107e9536-5fd4-4b44-891e-9e77eb5ca9ab"),
                            Email = "alvin@usu.ac.id",
                            Name = "Alvin",
                            Password = "alvin123"
                        },
                        new
                        {
                            Id = new Guid("6e8173db-65aa-4b55-b030-eee00927cd39"),
                            Email = "febriando@usu.ac.id",
                            Name = "Febriando",
                            Password = "febriando123"
                        });
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.Property<Guid>("AnsweredById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveysId")
                        .HasColumnType("uuid");

                    b.HasKey("AnsweredById", "SurveysId");

                    b.HasIndex("SurveysId");

                    b.ToTable("SurveyUser");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.SurveyQuestion", "SurveyQuestion")
                        .WithMany()
                        .HasForeignKey("SurveyQuestionSurveyId", "SurveyQuestionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", "Survey")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AnsweredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Navigation("SurveyQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
