// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Questionnaire.Infrastructure.Persistence.Postgres;

#nullable disable

namespace Questionnaire.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230601061134_SeedSurveys")]
    partial class SeedSurveys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SurveyQuestionQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveyQuestionSurveyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionSurveyId", "SurveyQuestionQuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e97e4f1e-d72e-43ad-92a0-2cbd28296bcf"),
                            Name = "Nabila",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("64805099-6e8a-4269-82a4-59642ec8a610"),
                            Name = "Hesti",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("fa1b6693-4f1c-4cd5-98c2-024d6fa6be19"),
                            Name = "Ajeng",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("ae0e8488-4119-487b-b56d-69f680e49655"),
                            Name = "Syahrini",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("0f27a418-23f4-40d9-8bcb-58a98be78aee"),
                            Name = "Laras",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("93fad230-28a8-438d-a8af-d0137d078382"),
                            Name = "Dalimin",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("5c7dfd25-206b-4f80-9876-15ad64a6afb6"),
                            Name = "Unggul",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("866596ec-8f55-4c67-9f9d-e71dcf7cae6b"),
                            Name = "Margana",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("57012468-2fee-45c7-997c-fe184d630541"),
                            Name = "Harjo",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("3a42af84-9f31-4d8a-a0f0-b9ee2f563639"),
                            Name = "Budi",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("7a244266-19a5-4527-8041-a4cb40d99d95"),
                            Name = "Radika",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("2c13893e-29a2-4d5b-ba50-f8e12a78607e"),
                            Name = "Kenzie",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("47ddf172-2abb-4e77-83ca-0b52ab5a4bed"),
                            Name = "Galak",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("bf1b32fd-3d22-4f17-8e5b-5faf55d6d427"),
                            Name = "Asmadi",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("86b7c189-370d-4018-8e62-0752c0e47f32"),
                            Name = "Prabu",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("a38a4944-8fbd-4e08-9f4c-4f1478acea01"),
                            Name = "Jamil",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("f05e1bf1-768c-4719-8a78-b68ba477d010"),
                            Name = "Digdaya",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("f739066d-bf4f-470f-8c3e-08af9a88bafb"),
                            Name = "Warsita",
                            Title = "Pak"
                        },
                        new
                        {
                            Id = new Guid("30ba4537-ba0b-4187-97f4-1b711cb4b58d"),
                            Name = "Raisa",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("a100dea5-b5ec-431e-b2b4-127bc58e19c1"),
                            Name = "Kiandra",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("4544202d-7d25-4b83-96eb-bcacd858c0cd"),
                            Name = "Eka",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("00416243-854e-464d-a79d-d6044618664e"),
                            Name = "Violet",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("57ab1244-8484-4b48-9ccf-ccb0ffb21166"),
                            Name = "Puspa",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("9e11454f-0e68-4473-b2f6-9ceeb57d9de0"),
                            Name = "Jamalia",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("dead4043-8e12-4dad-b8c1-b03c7af2ef10"),
                            Name = "Chelsea",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("7fbba595-86f8-413b-9afd-03f2fe1970e4"),
                            Name = "Tantri",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("3c16908e-ace6-430d-b360-d63c2032dbcc"),
                            Name = "Nova",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("bd160a9b-3e8d-4530-85ee-53cbc721be00"),
                            Name = "Hafshah",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("2415fe09-a849-4cf7-b5dd-63e0d2613307"),
                            Name = "Ayu",
                            Title = "Bu"
                        },
                        new
                        {
                            Id = new Guid("a18dcd39-1de8-4b93-a237-8936c3f1f0a0"),
                            Name = "Safina",
                            Title = "Bu"
                        });
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e"),
                            Advice = "memberikan kesempatan bertanya di dalam kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di dalam kelas?"
                        },
                        new
                        {
                            Id = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9"),
                            Advice = "memberikan kesempatan bertanya di luar kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di luar kelas?"
                        },
                        new
                        {
                            Id = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803"),
                            Advice = "memanfaatkan fitur forum yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur forum e-learning?"
                        },
                        new
                        {
                            Id = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f"),
                            Advice = "memanfaatkan fitur kuis yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur kuis e-learning?"
                        },
                        new
                        {
                            Id = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d"),
                            Advice = "memanfaatkan fitur konferensi video yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur konferensi video e-learning?"
                        },
                        new
                        {
                            Id = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e"),
                            Advice = "memberikan nilai tugas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil tugas"
                        },
                        new
                        {
                            Id = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c"),
                            Advice = "memberikan nilai kuis secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil kuis"
                        },
                        new
                        {
                            Id = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72"),
                            Advice = "memberikan nilai uts dan uas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil uts dan uas"
                        },
                        new
                        {
                            Id = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9"),
                            Advice = "hadir tepat waktu (maksimal 15 menit keterlambatan)",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah dosen hadir tepat waktu"
                        },
                        new
                        {
                            Id = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459"),
                            Advice = "memberikan perkuliahan sesuai dengan sesi yang sudah dialokasikan",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah perkuliahan dilaksanakan sesuai dengan alokasi waktu"
                        },
                        new
                        {
                            Id = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925"),
                            Advice = "menyampaikan materi sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah materi yang disampaikan sudah sesuai dengan rpp dan rps?"
                        },
                        new
                        {
                            Id = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552"),
                            Advice = "memberikan tugas sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah tugas yang diberikan sesuai dengan beban studi?"
                        },
                        new
                        {
                            Id = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de"),
                            Advice = "mencari referensi terkait materi yang diajarkan",
                            Section = "penguasaan materi",
                            Title = "Apakah dosen menguasai materi perkuliahan dengan baik?"
                        });
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AspectCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 4, 2),
                            LecturerId = new Guid("47ddf172-2abb-4e77-83ca-0b52ab5a4bed"),
                            Place = "C",
                            QuestionCount = 13,
                            Subject = "Pendidikan Agama Budha"
                        },
                        new
                        {
                            Id = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 5, 17),
                            LecturerId = new Guid("f05e1bf1-768c-4719-8a78-b68ba477d010"),
                            Place = "C",
                            QuestionCount = 13,
                            Subject = "Pemrograman Integrative"
                        },
                        new
                        {
                            Id = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 3, 31),
                            LecturerId = new Guid("a100dea5-b5ec-431e-b2b4-127bc58e19c1"),
                            Place = "B",
                            QuestionCount = 13,
                            Subject = "Matematika Diskrit"
                        },
                        new
                        {
                            Id = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 5, 15),
                            LecturerId = new Guid("57ab1244-8484-4b48-9ccf-ccb0ffb21166"),
                            Place = "B",
                            QuestionCount = 13,
                            Subject = "Manajemen Proyek Teknologi Informasi"
                        },
                        new
                        {
                            Id = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 3, 28),
                            LecturerId = new Guid("3c16908e-ace6-430d-b360-d63c2032dbcc"),
                            Place = "A",
                            QuestionCount = 13,
                            Subject = "Jaminan dan Keamanan Informasi"
                        },
                        new
                        {
                            Id = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 5, 13),
                            LecturerId = new Guid("a18dcd39-1de8-4b93-a237-8936c3f1f0a0"),
                            Place = "A",
                            QuestionCount = 13,
                            Subject = "Dasar Pemrograman"
                        },
                        new
                        {
                            Id = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 3, 26),
                            LecturerId = new Guid("fa1b6693-4f1c-4cd5-98c2-024d6fa6be19"),
                            Place = "C",
                            QuestionCount = 13,
                            Subject = "Desain Interaksi"
                        },
                        new
                        {
                            Id = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 5, 10),
                            LecturerId = new Guid("5c7dfd25-206b-4f80-9876-15ad64a6afb6"),
                            Place = "C",
                            QuestionCount = 13,
                            Subject = "Pendidikan Agama Konghucu"
                        },
                        new
                        {
                            Id = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 3, 24),
                            LecturerId = new Guid("3a42af84-9f31-4d8a-a0f0-b9ee2f563639"),
                            Place = "B",
                            QuestionCount = 13,
                            Subject = "Pemrograman Integrative"
                        },
                        new
                        {
                            Id = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            AspectCount = 6,
                            Date = new DateOnly(2023, 5, 8),
                            LecturerId = new Guid("47ddf172-2abb-4e77-83ca-0b52ab5a4bed"),
                            Place = "B",
                            QuestionCount = 13,
                            Subject = "Matematika Diskrit"
                        });
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("SurveyId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("SurveyQuestions");

                    b.HasData(
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552")
                        },
                        new
                        {
                            SurveyId = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            QuestionId = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de")
                        });
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("571fbf8b-eca4-c69c-da37-aafc9cea140a"),
                            Email = "reksa@usu.ac.id",
                            Name = "Reksa",
                            Password = "reksa123"
                        },
                        new
                        {
                            Id = new Guid("3ff772fc-64ec-b453-0608-ef2343ba4c4c"),
                            Email = "restu@usu.ac.id",
                            Name = "Restu",
                            Password = "restu123"
                        },
                        new
                        {
                            Id = new Guid("28cf256d-db33-a30a-32d9-354ae98b858f"),
                            Email = "jamal@usu.ac.id",
                            Name = "Jamal",
                            Password = "jamal123"
                        },
                        new
                        {
                            Id = new Guid("10a7d7de-527b-91c1-5fa9-7a71905cbdd1"),
                            Email = "ina@usu.ac.id",
                            Name = "Ina",
                            Password = "ina123"
                        },
                        new
                        {
                            Id = new Guid("f8808a4f-cac3-7f78-8b7a-bf98372cf514"),
                            Email = "dacin@usu.ac.id",
                            Name = "Dacin",
                            Password = "dacin123"
                        },
                        new
                        {
                            Id = new Guid("e0583dc0-410a-6d2f-b74b-04bfdefd2e56"),
                            Email = "ana@usu.ac.id",
                            Name = "Ana",
                            Password = "ana123"
                        },
                        new
                        {
                            Id = new Guid("c830ef31-b952-5be6-e41b-4ae684ce6699"),
                            Email = "surya@usu.ac.id",
                            Name = "Surya",
                            Password = "surya123"
                        },
                        new
                        {
                            Id = new Guid("b008a2a2-3099-4a9e-10ec-8f0d2b9e9fdb"),
                            Email = "raina@usu.ac.id",
                            Name = "Raina",
                            Password = "raina123"
                        },
                        new
                        {
                            Id = new Guid("99e15513-a7e1-3855-3cbd-d434d26fd71d"),
                            Email = "kasusra@usu.ac.id",
                            Name = "Kasusra",
                            Password = "kasusra123"
                        },
                        new
                        {
                            Id = new Guid("81b90884-1f29-260c-698e-195c79400f60"),
                            Email = "jasmin@usu.ac.id",
                            Name = "Jasmin",
                            Password = "jasmin123"
                        },
                        new
                        {
                            Id = new Guid("6991baf5-9670-14c3-955e-5f831f1048a2"),
                            Email = "darmanto@usu.ac.id",
                            Name = "Darmanto",
                            Password = "darmanto123"
                        },
                        new
                        {
                            Id = new Guid("51696d66-0db8-037a-c12f-a4aac6e180e5"),
                            Email = "bella@usu.ac.id",
                            Name = "Bella",
                            Password = "bella123"
                        },
                        new
                        {
                            Id = new Guid("394220d7-85ff-f131-ee00-e9d16db2b927"),
                            Email = "teguh@usu.ac.id",
                            Name = "Teguh",
                            Password = "teguh123"
                        },
                        new
                        {
                            Id = new Guid("221ad348-fc47-dfe8-1ad0-2ef81482f16a"),
                            Email = "safina@usu.ac.id",
                            Name = "Safina",
                            Password = "safina123"
                        },
                        new
                        {
                            Id = new Guid("0af285b9-738f-cda0-46a1-741fba5329ac"),
                            Email = "kemal@usu.ac.id",
                            Name = "Kemal",
                            Password = "kemal123"
                        },
                        new
                        {
                            Id = new Guid("f2cb382a-ebd6-bb57-7372-b946612462ef"),
                            Email = "keisha@usu.ac.id",
                            Name = "Keisha",
                            Password = "keisha123"
                        },
                        new
                        {
                            Id = new Guid("daa3eb9b-621e-aa0e-9f42-fe6d08f49a31"),
                            Email = "eman@usu.ac.id",
                            Name = "Eman",
                            Password = "eman123"
                        },
                        new
                        {
                            Id = new Guid("c27b9d0c-d965-98c5-cb13-4394afc5d373"),
                            Email = "cinthia@usu.ac.id",
                            Name = "Cinthia",
                            Password = "cinthia123"
                        },
                        new
                        {
                            Id = new Guid("aa53507c-51ad-867c-f8e4-89bb55960bb6"),
                            Email = "viman@usu.ac.id",
                            Name = "Viman",
                            Password = "viman123"
                        },
                        new
                        {
                            Id = new Guid("932c03ed-c8f5-7433-24b4-cee2fc6643f8"),
                            Email = "shakila@usu.ac.id",
                            Name = "Shakila",
                            Password = "shakila123"
                        },
                        new
                        {
                            Id = new Guid("7b04b65e-403c-63ea-5085-1309a3377c3b"),
                            Email = "lurhur@usu.ac.id",
                            Name = "Lurhur",
                            Password = "lurhur123"
                        },
                        new
                        {
                            Id = new Guid("63dc68cf-b784-51a2-7d56-58304908b47d"),
                            Email = "laras@usu.ac.id",
                            Name = "Laras",
                            Password = "laras123"
                        },
                        new
                        {
                            Id = new Guid("4bb41b40-2ecb-3f59-a926-9e57f0d8edc0"),
                            Email = "gada@usu.ac.id",
                            Name = "Gada",
                            Password = "gada123"
                        },
                        new
                        {
                            Id = new Guid("338dceb1-a613-2d10-d5f7-e37e97a92502"),
                            Email = "diana@usu.ac.id",
                            Name = "Diana",
                            Password = "diana123"
                        },
                        new
                        {
                            Id = new Guid("1b658122-1d5b-1cc7-02c8-28a53e7a5d44"),
                            Email = "yusuf@usu.ac.id",
                            Name = "Yusuf",
                            Password = "yusuf123"
                        },
                        new
                        {
                            Id = new Guid("043d3393-94a2-0a7e-2e98-6dcce44a9687"),
                            Email = "tantri@usu.ac.id",
                            Name = "Tantri",
                            Password = "tantri123"
                        },
                        new
                        {
                            Id = new Guid("ec15e604-0cea-f835-5a69-b2f38b1bcec9"),
                            Email = "martaka@usu.ac.id",
                            Name = "Martaka",
                            Password = "martaka123"
                        },
                        new
                        {
                            Id = new Guid("d4ee9975-8331-e6ec-873a-f81a32ec070c"),
                            Email = "maimunah@usu.ac.id",
                            Name = "Maimunah",
                            Password = "maimunah123"
                        },
                        new
                        {
                            Id = new Guid("bcc64ce6-fa79-d4a4-b30a-3d42d9bd3f4e"),
                            Email = "ina@usu.ac.id",
                            Name = "Ina",
                            Password = "ina123"
                        },
                        new
                        {
                            Id = new Guid("a49efe57-72c1-c35b-dfdb-82697f8d7791"),
                            Email = "cengkir@usu.ac.id",
                            Name = "Cengkir",
                            Password = "cengkir123"
                        },
                        new
                        {
                            Id = new Guid("8c77b1c8-e908-b112-0cac-c790265eb0d3"),
                            Email = "ana@usu.ac.id",
                            Name = "Ana",
                            Password = "ana123"
                        },
                        new
                        {
                            Id = new Guid("754f6439-6050-9fc9-387c-0db7cd2fe816"),
                            Email = "saiful@usu.ac.id",
                            Name = "Saiful",
                            Password = "saiful123"
                        },
                        new
                        {
                            Id = new Guid("5d2716aa-d897-8d80-644d-52de74ff2158"),
                            Email = "raina@usu.ac.id",
                            Name = "Raina",
                            Password = "raina123"
                        },
                        new
                        {
                            Id = new Guid("45ffc91b-4fdf-7c37-911e-97051ad0599a"),
                            Email = "kasiran@usu.ac.id",
                            Name = "Kasiran",
                            Password = "kasiran123"
                        },
                        new
                        {
                            Id = new Guid("2dd87c8c-c627-6aee-bdee-dc2cc1a191dd"),
                            Email = "jasmin@usu.ac.id",
                            Name = "Jasmin",
                            Password = "jasmin123"
                        },
                        new
                        {
                            Id = new Guid("15b02ffd-3e6e-58a6-e9bf-22536871ca1f"),
                            Email = "darmana@usu.ac.id",
                            Name = "Darmana",
                            Password = "darmana123"
                        },
                        new
                        {
                            Id = new Guid("fe88e16e-b5b6-465d-1690-677a0f420262"),
                            Email = "almira@usu.ac.id",
                            Name = "Almira",
                            Password = "almira123"
                        },
                        new
                        {
                            Id = new Guid("e66094df-2dfd-3414-4260-aca1b5133ba4"),
                            Email = "tasnim@usu.ac.id",
                            Name = "Tasnim",
                            Password = "tasnim123"
                        },
                        new
                        {
                            Id = new Guid("ce394750-a445-23cb-6e31-f1c85ce373e7"),
                            Email = "sadina@usu.ac.id",
                            Name = "Sadina",
                            Password = "sadina123"
                        },
                        new
                        {
                            Id = new Guid("b611fac1-1b8d-1182-9b02-37ef03b4ab29"),
                            Email = "kenzie@usu.ac.id",
                            Name = "Kenzie",
                            Password = "kenzie123"
                        },
                        new
                        {
                            Id = new Guid("9ee9ac32-93d4-ff39-c7d2-7c16aa85e46b"),
                            Email = "kasiyah@usu.ac.id",
                            Name = "Kasiyah",
                            Password = "kasiyah123"
                        },
                        new
                        {
                            Id = new Guid("86c15fa3-0a1c-edf0-f3a3-c13d50551cae"),
                            Email = "eluh@usu.ac.id",
                            Name = "Eluh",
                            Password = "eluh123"
                        },
                        new
                        {
                            Id = new Guid("6f9a1214-8163-dca8-2074-0664f72655f0"),
                            Email = "cinta@usu.ac.id",
                            Name = "Cinta",
                            Password = "cinta123"
                        },
                        new
                        {
                            Id = new Guid("5772c484-f9ab-ca5f-4c44-4c8b9ef78d33"),
                            Email = "vega@usu.ac.id",
                            Name = "Vega",
                            Password = "vega123"
                        },
                        new
                        {
                            Id = new Guid("3f4a77f5-70f3-b816-7815-91b245c7c575"),
                            Email = "silvia@usu.ac.id",
                            Name = "Silvia",
                            Password = "silvia123"
                        },
                        new
                        {
                            Id = new Guid("27232a66-e73a-a6cd-a5e6-d6d9eb98feb8"),
                            Email = "lulut@usu.ac.id",
                            Name = "Lulut",
                            Password = "lulut123"
                        },
                        new
                        {
                            Id = new Guid("0ffbddd7-5f82-9484-d1b7-1b01926936fa"),
                            Email = "laila@usu.ac.id",
                            Name = "Laila",
                            Password = "laila123"
                        },
                        new
                        {
                            Id = new Guid("f7d38f48-d6c9-833b-fd87-612839396f3c"),
                            Email = "eja@usu.ac.id",
                            Name = "Eja",
                            Password = "eja123"
                        },
                        new
                        {
                            Id = new Guid("e0ab42b9-4d11-71f2-2a58-a64fe00aa77f"),
                            Email = "diah@usu.ac.id",
                            Name = "Diah",
                            Password = "diah123"
                        },
                        new
                        {
                            Id = new Guid("c884f52a-c559-5faa-5629-eb7686dbdfc1"),
                            Email = "yahya@usu.ac.id",
                            Name = "Yahya",
                            Password = "yahya123"
                        },
                        new
                        {
                            Id = new Guid("b05ca89b-3ca0-4d61-82f9-309d2dab1804"),
                            Email = "tantri@usu.ac.id",
                            Name = "Tantri",
                            Password = "tantri123"
                        },
                        new
                        {
                            Id = new Guid("98345a0c-b3e8-3c18-afca-76c4d47c5046"),
                            Email = "marsudi@usu.ac.id",
                            Name = "Marsudi",
                            Password = "marsudi123"
                        },
                        new
                        {
                            Id = new Guid("800c0d7d-2b2f-2acf-db9b-bbeb7b4d8889"),
                            Email = "maimunah@usu.ac.id",
                            Name = "Maimunah",
                            Password = "maimunah123"
                        },
                        new
                        {
                            Id = new Guid("68e5c0ee-a277-1886-076b-0012211dc1cb"),
                            Email = "gandi@usu.ac.id",
                            Name = "Gandi",
                            Password = "gandi123"
                        },
                        new
                        {
                            Id = new Guid("51bd735f-1abe-063d-343c-4539c8eef90e"),
                            Email = "eli@usu.ac.id",
                            Name = "Eli",
                            Password = "eli123"
                        },
                        new
                        {
                            Id = new Guid("399525d0-9106-f4f4-600d-8b606fbf3250"),
                            Email = "among@usu.ac.id",
                            Name = "Among",
                            Password = "among123"
                        },
                        new
                        {
                            Id = new Guid("216dd841-084e-e3ac-8cdd-d087168f6a92"),
                            Email = "usyi@usu.ac.id",
                            Name = "Usyi",
                            Password = "usyi123"
                        },
                        new
                        {
                            Id = new Guid("09468bb2-8095-d163-b9ae-15aebc60a2d5"),
                            Email = "mahdi@usu.ac.id",
                            Name = "Mahdi",
                            Password = "mahdi123"
                        },
                        new
                        {
                            Id = new Guid("f11e3d23-f7dd-bf1a-e57f-5ad56331db17"),
                            Email = "natalia@usu.ac.id",
                            Name = "Natalia",
                            Password = "natalia123"
                        },
                        new
                        {
                            Id = new Guid("daf6f094-6e24-add1-114f-a0fc0a01135a"),
                            Email = "harimurti@usu.ac.id",
                            Name = "Harimurti",
                            Password = "harimurti123"
                        },
                        new
                        {
                            Id = new Guid("c2cfa305-e66c-9c88-3e20-e523b0d24c9c"),
                            Email = "farah@usu.ac.id",
                            Name = "Farah",
                            Password = "farah123"
                        },
                        new
                        {
                            Id = new Guid("aaa75676-5db4-8a3f-6af1-2a4a57a384df"),
                            Email = "bagas@usu.ac.id",
                            Name = "Bagas",
                            Password = "bagas123"
                        },
                        new
                        {
                            Id = new Guid("927f08e7-d4fb-78f6-96c1-6f71fe73bc21"),
                            Email = "winda@usu.ac.id",
                            Name = "Winda",
                            Password = "winda123"
                        },
                        new
                        {
                            Id = new Guid("7a57bb58-4c43-66ae-c392-b598a544f563"),
                            Email = "nyoman@usu.ac.id",
                            Name = "Nyoman",
                            Password = "nyoman123"
                        },
                        new
                        {
                            Id = new Guid("62306ec9-c38a-5465-ef63-fabf4b152da6"),
                            Email = "oni@usu.ac.id",
                            Name = "Oni",
                            Password = "oni123"
                        },
                        new
                        {
                            Id = new Guid("4b08213a-3ad2-431c-1b33-3fe7f2e566e8"),
                            Email = "heryanto@usu.ac.id",
                            Name = "Heryanto",
                            Password = "heryanto123"
                        },
                        new
                        {
                            Id = new Guid("33e0d3ab-b21a-31d3-4804-840e99b69e2b"),
                            Email = "gina@usu.ac.id",
                            Name = "Gina",
                            Password = "gina123"
                        },
                        new
                        {
                            Id = new Guid("1bb8861c-2961-1f8a-74d5-ca354087d66d"),
                            Email = "bala@usu.ac.id",
                            Name = "Bala",
                            Password = "bala123"
                        },
                        new
                        {
                            Id = new Guid("0391398c-a1a9-0d41-a0a5-0f5ce6570fb0"),
                            Email = "vinsen@usu.ac.id",
                            Name = "Vinsen",
                            Password = "vinsen123"
                        },
                        new
                        {
                            Id = new Guid("eb69ecfd-18f0-fcf8-cd76-54838d2847f2"),
                            Email = "silvia@usu.ac.id",
                            Name = "Silvia",
                            Password = "silvia123"
                        },
                        new
                        {
                            Id = new Guid("d3419e6e-8f38-eab0-f947-99aa34f98035"),
                            Email = "luluh@usu.ac.id",
                            Name = "Luluh",
                            Password = "luluh123"
                        },
                        new
                        {
                            Id = new Guid("bc1951df-0780-d867-2517-dfd1dbc9b877"),
                            Email = "laila@usu.ac.id",
                            Name = "Laila",
                            Password = "laila123"
                        },
                        new
                        {
                            Id = new Guid("a4f20450-7ec7-c61e-52e8-24f8819af0b9"),
                            Email = "emin@usu.ac.id",
                            Name = "Emin",
                            Password = "emin123"
                        },
                        new
                        {
                            Id = new Guid("8ccab6c1-f50f-b4d5-7eb9-691f286b29fc"),
                            Email = "diah@usu.ac.id",
                            Name = "Diah",
                            Password = "diah123"
                        },
                        new
                        {
                            Id = new Guid("74a26932-6d56-a38c-aa89-ae46cf3b613e"),
                            Email = "xanana@usu.ac.id",
                            Name = "Xanana",
                            Password = "xanana123"
                        },
                        new
                        {
                            Id = new Guid("5c7b1ca3-e49e-9143-d75a-f46d760c9a81"),
                            Email = "tina@usu.ac.id",
                            Name = "Tina",
                            Password = "tina123"
                        },
                        new
                        {
                            Id = new Guid("4453cf14-5be6-7ffa-032b-39941cddd2c3"),
                            Email = "mariadi@usu.ac.id",
                            Name = "Mariadi",
                            Password = "mariadi123"
                        },
                        new
                        {
                            Id = new Guid("2d2b8185-d32d-6db2-2ffb-7ebbc3ae0a06"),
                            Email = "maida@usu.ac.id",
                            Name = "Maida",
                            Password = "maida123"
                        },
                        new
                        {
                            Id = new Guid("150334f6-4a75-5c69-5ccc-c3e26a7e4348"),
                            Email = "gandewa@usu.ac.id",
                            Name = "Gandewa",
                            Password = "gandewa123"
                        },
                        new
                        {
                            Id = new Guid("fddce767-c1bc-4a20-889d-0909114f7b8a"),
                            Email = "elisa@usu.ac.id",
                            Name = "Elisa",
                            Password = "elisa123"
                        },
                        new
                        {
                            Id = new Guid("e5b49ad8-3904-38d7-b46d-4e30b720b4cd"),
                            Email = "akarsana@usu.ac.id",
                            Name = "Akarsana",
                            Password = "akarsana123"
                        },
                        new
                        {
                            Id = new Guid("cd8c4c49-b04c-268e-e13e-93575ef0ec0f"),
                            Email = "umi@usu.ac.id",
                            Name = "Umi",
                            Password = "umi123"
                        },
                        new
                        {
                            Id = new Guid("b664ffba-2793-1445-0d0f-d87e05c12452"),
                            Email = "mahmud@usu.ac.id",
                            Name = "Mahmud",
                            Password = "mahmud123"
                        },
                        new
                        {
                            Id = new Guid("9e3db22b-9fdb-03fc-39df-1ea6ac925d94"),
                            Email = "nabila@usu.ac.id",
                            Name = "Nabila",
                            Password = "nabila123"
                        },
                        new
                        {
                            Id = new Guid("8615649c-1622-f1b4-66b0-63cd526295d7"),
                            Email = "hardi@usu.ac.id",
                            Name = "Hardi",
                            Password = "hardi123"
                        },
                        new
                        {
                            Id = new Guid("6eed170d-8e6a-df6b-9281-a8f4f933ce19"),
                            Email = "faizah@usu.ac.id",
                            Name = "Faizah",
                            Password = "faizah123"
                        },
                        new
                        {
                            Id = new Guid("56c5ca7e-05b2-cd22-be52-ed1ba004065c"),
                            Email = "atmaja@usu.ac.id",
                            Name = "Atmaja",
                            Password = "atmaja123"
                        },
                        new
                        {
                            Id = new Guid("3e9e7def-7cf9-bcd9-eb22-334247d43e9e"),
                            Email = "winda@usu.ac.id",
                            Name = "Winda",
                            Password = "winda123"
                        },
                        new
                        {
                            Id = new Guid("27762f60-f441-aa90-17f3-7869eda577e0"),
                            Email = "najam@usu.ac.id",
                            Name = "Najam",
                            Password = "najam123"
                        },
                        new
                        {
                            Id = new Guid("0f4ee2d1-6b88-9847-43c4-bd909476af23"),
                            Email = "oni@usu.ac.id",
                            Name = "Oni",
                            Password = "oni123"
                        },
                        new
                        {
                            Id = new Guid("f7279542-e2d0-86fe-7094-02b73b46e865"),
                            Email = "hendri@usu.ac.id",
                            Name = "Hendri",
                            Password = "hendri123"
                        },
                        new
                        {
                            Id = new Guid("dfff48b3-5a18-74b6-9c65-48dee21720a8"),
                            Email = "gina@usu.ac.id",
                            Name = "Gina",
                            Password = "gina123"
                        },
                        new
                        {
                            Id = new Guid("c7d7fa24-d15f-636d-c836-8d0588e858ea"),
                            Email = "baktiono@usu.ac.id",
                            Name = "Baktiono",
                            Password = "baktiono123"
                        },
                        new
                        {
                            Id = new Guid("afafad94-48a7-5124-f506-d22c2fb8912d"),
                            Email = "yuni@usu.ac.id",
                            Name = "Yuni",
                            Password = "yuni123"
                        },
                        new
                        {
                            Id = new Guid("98886005-c0ee-3fdb-21d7-1753d689c96f"),
                            Email = "prabu@usu.ac.id",
                            Name = "Prabu",
                            Password = "prabu123"
                        },
                        new
                        {
                            Id = new Guid("80601376-3736-2d92-4da8-5d7a7d5a02b1"),
                            Email = "puji@usu.ac.id",
                            Name = "Puji",
                            Password = "puji123"
                        },
                        new
                        {
                            Id = new Guid("6838c5e7-ae7e-1c49-7a78-a2a1232a3af4"),
                            Email = "ihsan@usu.ac.id",
                            Name = "Ihsan",
                            Password = "ihsan123"
                        },
                        new
                        {
                            Id = new Guid("41cdc211-9ad2-44df-9ad0-122014cd918b"),
                            Email = "admin@usu.ac.id",
                            Name = "Admin",
                            Password = "admin123"
                        },
                        new
                        {
                            Id = new Guid("107e9536-5fd4-4b44-891e-9e77eb5ca9ab"),
                            Email = "alvin@usu.ac.id",
                            Name = "Alvin",
                            Password = "alvin123"
                        },
                        new
                        {
                            Id = new Guid("6e8173db-65aa-4b55-b030-eee00927cd39"),
                            Email = "febriando@usu.ac.id",
                            Name = "Febriando",
                            Password = "febriando123"
                        });
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.Property<Guid>("AnsweredById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveysId")
                        .HasColumnType("uuid");

                    b.HasKey("AnsweredById", "SurveysId");

                    b.HasIndex("SurveysId");

                    b.ToTable("SurveyUser");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.SurveyQuestion", "SurveyQuestion")
                        .WithMany()
                        .HasForeignKey("SurveyQuestionSurveyId", "SurveyQuestionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", "Survey")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AnsweredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Navigation("SurveyQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
