// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Questionnaire.Infrastructure.Persistence.Postgres;

#nullable disable

namespace Questionnaire.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230530060728_AddAnsweredBy")]
    partial class AddAnsweredBy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SurveyQuestionQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveyQuestionSurveyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionSurveyId", "SurveyQuestionQuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e"),
                            Advice = "memberikan kesempatan bertanya di dalam kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di dalam kelas?"
                        },
                        new
                        {
                            Id = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9"),
                            Advice = "memberikan kesempatan bertanya di luar kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di luar kelas?"
                        },
                        new
                        {
                            Id = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803"),
                            Advice = "memanfaatkan fitur forum yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur forum e-learning?"
                        },
                        new
                        {
                            Id = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f"),
                            Advice = "memanfaatkan fitur kuis yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur kuis e-learning?"
                        },
                        new
                        {
                            Id = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d"),
                            Advice = "memanfaatkan fitur konferensi video yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur konferensi video e-learning?"
                        },
                        new
                        {
                            Id = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e"),
                            Advice = "memberikan nilai tugas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil tugas"
                        },
                        new
                        {
                            Id = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c"),
                            Advice = "memberikan nilai kuis secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil kuis"
                        },
                        new
                        {
                            Id = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72"),
                            Advice = "memberikan nilai uts dan uas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil uts dan uas"
                        },
                        new
                        {
                            Id = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9"),
                            Advice = "hadir tepat waktu (maksimal 15 menit keterlambatan)",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah dosen hadir tepat waktu"
                        },
                        new
                        {
                            Id = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459"),
                            Advice = "memberikan perkuliahan sesuai dengan sesi yang sudah dialokasikan",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah perkuliahan dilaksanakan sesuai dengan alokasi waktu"
                        },
                        new
                        {
                            Id = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925"),
                            Advice = "menyampaikan materi sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah materi yang disampaikan sudah sesuai dengan rpp dan rps?"
                        },
                        new
                        {
                            Id = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552"),
                            Advice = "memberikan tugas sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah tugas yang diberikan sesuai dengan beban studi?"
                        },
                        new
                        {
                            Id = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de"),
                            Advice = "mencari referensi terkait materi yang diajarkan",
                            Section = "penguasaan materi",
                            Title = "Apakah dosen menguasai materi perkuliahan dengan baik?"
                        });
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AspectCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("SurveyId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("908aa701-4f90-f5c6-4eb1-e2d06d6f3e25"),
                            Email = "olga@usu.ac.id",
                            Name = "Olga",
                            Password = "Olga123"
                        },
                        new
                        {
                            Id = new Guid("803e1e6b-24ed-9380-d9ea-7ffa3747c54e"),
                            Email = "bala@usu.ac.id",
                            Name = "Bala",
                            Password = "Bala123"
                        },
                        new
                        {
                            Id = new Guid("9694735a-f2c4-70a8-f1e1-d50aab2d3e9e"),
                            Email = "padma@usu.ac.id",
                            Name = "Padma",
                            Password = "Padma123"
                        },
                        new
                        {
                            Id = new Guid("728014a7-9978-044d-d68c-a10a1be93e40"),
                            Email = "emil@usu.ac.id",
                            Name = "Emil",
                            Password = "Emil123"
                        },
                        new
                        {
                            Id = new Guid("c5966cf9-e974-8a95-4bbf-55c55e8a92e2"),
                            Email = "ozy@usu.ac.id",
                            Name = "Ozy",
                            Password = "Ozy123"
                        },
                        new
                        {
                            Id = new Guid("c58ffb89-bbef-995f-c144-9f733458cf8f"),
                            Email = "tania@usu.ac.id",
                            Name = "Tania",
                            Password = "Tania123"
                        },
                        new
                        {
                            Id = new Guid("fa1e3a71-9f8a-8536-0286-5f4e70e06d45"),
                            Email = "caraka@usu.ac.id",
                            Name = "Caraka",
                            Password = "Caraka123"
                        },
                        new
                        {
                            Id = new Guid("8c3f8d6a-5105-4ce9-74b2-648ee8e8c390"),
                            Email = "asirwada@usu.ac.id",
                            Name = "Asirwada",
                            Password = "Asirwada123"
                        },
                        new
                        {
                            Id = new Guid("3c6f2ece-3d05-6cd4-a952-2a010c89b116"),
                            Email = "jelita@usu.ac.id",
                            Name = "Jelita",
                            Password = "Jelita123"
                        },
                        new
                        {
                            Id = new Guid("1e02616b-663d-1e6c-9ccb-177258ee759f"),
                            Email = "kurnia@usu.ac.id",
                            Name = "Kurnia",
                            Password = "Kurnia123"
                        },
                        new
                        {
                            Id = new Guid("e98ce00a-1469-337b-45d7-7e97d33badfc"),
                            Email = "tina@usu.ac.id",
                            Name = "Tina",
                            Password = "Tina123"
                        },
                        new
                        {
                            Id = new Guid("2c3a3125-62e1-cb70-c046-3cdb64eb6d36"),
                            Email = "umay@usu.ac.id",
                            Name = "Umay",
                            Password = "Umay123"
                        },
                        new
                        {
                            Id = new Guid("965f6fa8-8e3f-adce-fa72-37a1ff8a6ddd"),
                            Email = "bala@usu.ac.id",
                            Name = "Bala",
                            Password = "Bala123"
                        },
                        new
                        {
                            Id = new Guid("04ac69e0-af89-e9be-a9a3-b69e103309c5"),
                            Email = "ana@usu.ac.id",
                            Name = "Ana",
                            Password = "Ana123"
                        },
                        new
                        {
                            Id = new Guid("e534f6d4-2be8-1a5c-18ed-754f43766a03"),
                            Email = "carla@usu.ac.id",
                            Name = "Carla",
                            Password = "Carla123"
                        },
                        new
                        {
                            Id = new Guid("92a0a7b3-a58a-5048-fd60-860d9f0df349"),
                            Email = "hartaka@usu.ac.id",
                            Name = "Hartaka",
                            Password = "Hartaka123"
                        },
                        new
                        {
                            Id = new Guid("1fd1eeb2-f67c-856d-a059-6fcb7d9c0090"),
                            Email = "talia@usu.ac.id",
                            Name = "Talia",
                            Password = "Talia123"
                        },
                        new
                        {
                            Id = new Guid("6db71b47-7d72-b4b7-de83-51d1fb38af48"),
                            Email = "lalita@usu.ac.id",
                            Name = "Lalita",
                            Password = "Lalita123"
                        },
                        new
                        {
                            Id = new Guid("dc054298-0ccc-2bae-9089-ea910cb10f94"),
                            Email = "caraka@usu.ac.id",
                            Name = "Caraka",
                            Password = "Caraka123"
                        },
                        new
                        {
                            Id = new Guid("74650f07-e324-98e6-d845-4fb7ff88b492"),
                            Email = "kamidin@usu.ac.id",
                            Name = "Kamidin",
                            Password = "Kamidin123"
                        },
                        new
                        {
                            Id = new Guid("cdd1c450-19d9-b9e5-e4f9-05fbfa3bc8ec"),
                            Email = "paulin@usu.ac.id",
                            Name = "Paulin",
                            Password = "Paulin123"
                        },
                        new
                        {
                            Id = new Guid("a2a88a81-a317-43ab-b0c6-d0ea0394a301"),
                            Email = "ismail@usu.ac.id",
                            Name = "Ismail",
                            Password = "Ismail123"
                        },
                        new
                        {
                            Id = new Guid("0d2e94d7-8a59-9c98-1edc-ae4bb95330f0"),
                            Email = "maria@usu.ac.id",
                            Name = "Maria",
                            Password = "Maria123"
                        },
                        new
                        {
                            Id = new Guid("2995aea4-4c58-d927-b8b2-384aa009d2c8"),
                            Email = "margana@usu.ac.id",
                            Name = "Margana",
                            Password = "Margana123"
                        },
                        new
                        {
                            Id = new Guid("fc38688c-64de-a99f-b877-58cbdd60390a"),
                            Email = "luthfi@usu.ac.id",
                            Name = "Luthfi",
                            Password = "Luthfi123"
                        },
                        new
                        {
                            Id = new Guid("1bba6d5e-945b-d883-5aa6-4701da8f2a7a"),
                            Email = "sadina@usu.ac.id",
                            Name = "Sadina",
                            Password = "Sadina123"
                        },
                        new
                        {
                            Id = new Guid("a089d177-8469-6c87-f5c4-93978ae11e52"),
                            Email = "kambali@usu.ac.id",
                            Name = "Kambali",
                            Password = "Kambali123"
                        },
                        new
                        {
                            Id = new Guid("a7fe81cd-1351-bbf6-8788-4f2b6743c6f7"),
                            Email = "queen@usu.ac.id",
                            Name = "Queen",
                            Password = "Queen123"
                        },
                        new
                        {
                            Id = new Guid("3e2d4b50-d4f6-acb7-8da4-0690416f030f"),
                            Email = "nurul@usu.ac.id",
                            Name = "Nurul",
                            Password = "Nurul123"
                        },
                        new
                        {
                            Id = new Guid("1e5b90f3-f418-31ad-3f5e-ce32873b6a7e"),
                            Email = "dewi@usu.ac.id",
                            Name = "Dewi",
                            Password = "Dewi123"
                        },
                        new
                        {
                            Id = new Guid("cd4474c7-eb1a-d04a-7fe9-8cf5563521de"),
                            Email = "mitra@usu.ac.id",
                            Name = "Mitra",
                            Password = "Mitra123"
                        },
                        new
                        {
                            Id = new Guid("11752492-3634-571e-112d-721a33ff1f2e"),
                            Email = "gasti@usu.ac.id",
                            Name = "Gasti",
                            Password = "Gasti123"
                        },
                        new
                        {
                            Id = new Guid("42cd424d-983d-9cc2-d8cc-86474594ad68"),
                            Email = "patricia@usu.ac.id",
                            Name = "Patricia",
                            Password = "Patricia123"
                        },
                        new
                        {
                            Id = new Guid("9f6a1773-ea51-0396-421a-b14007ce52f4"),
                            Email = "natalia@usu.ac.id",
                            Name = "Natalia",
                            Password = "Natalia123"
                        },
                        new
                        {
                            Id = new Guid("dbea875c-7dd7-64dc-2045-231b2c42ea83"),
                            Email = "cagak@usu.ac.id",
                            Name = "Cagak",
                            Password = "Cagak123"
                        },
                        new
                        {
                            Id = new Guid("047d95ca-7507-ff36-eb22-692ed4723ccf"),
                            Email = "bakti@usu.ac.id",
                            Name = "Bakti",
                            Password = "Bakti123"
                        },
                        new
                        {
                            Id = new Guid("9b34714c-3056-70fb-da2d-a9bef3e63bde"),
                            Email = "jane@usu.ac.id",
                            Name = "Jane",
                            Password = "Jane123"
                        },
                        new
                        {
                            Id = new Guid("4fb224db-6c57-6f9e-83db-1ebf14ba09fd"),
                            Email = "adinata@usu.ac.id",
                            Name = "Adinata",
                            Password = "Adinata123"
                        },
                        new
                        {
                            Id = new Guid("e8b1bc82-79ab-b83e-da25-3d287e2b6580"),
                            Email = "maria@usu.ac.id",
                            Name = "Maria",
                            Password = "Maria123"
                        },
                        new
                        {
                            Id = new Guid("2d04cb84-a961-97a3-8fbf-fa0e734af9fe"),
                            Email = "dian@usu.ac.id",
                            Name = "Dian",
                            Password = "Dian123"
                        },
                        new
                        {
                            Id = new Guid("30f149e6-b2cd-bf6a-3bda-0423abfd03b3"),
                            Email = "agnes@usu.ac.id",
                            Name = "Agnes",
                            Password = "Agnes123"
                        },
                        new
                        {
                            Id = new Guid("dc9997bd-7b40-0be6-d4df-de69fcd006d9"),
                            Email = "radika@usu.ac.id",
                            Name = "Radika",
                            Password = "Radika123"
                        },
                        new
                        {
                            Id = new Guid("69fc612d-ad16-7d86-7b92-29915dc8ce22"),
                            Email = "eva@usu.ac.id",
                            Name = "Eva",
                            Password = "Eva123"
                        },
                        new
                        {
                            Id = new Guid("2baa9291-e792-c3c5-c53d-51c8a3da0aec"),
                            Email = "julia@usu.ac.id",
                            Name = "Julia",
                            Password = "Julia123"
                        },
                        new
                        {
                            Id = new Guid("fddd85a6-e6b1-0437-d35c-4975caf69093"),
                            Email = "endah@usu.ac.id",
                            Name = "Endah",
                            Password = "Endah123"
                        },
                        new
                        {
                            Id = new Guid("b8e9f070-9e7c-cfa4-fc4b-0ceffe79a5e4"),
                            Email = "arsipatra@usu.ac.id",
                            Name = "Arsipatra",
                            Password = "Arsipatra123"
                        },
                        new
                        {
                            Id = new Guid("6b7e3d78-68dc-0741-de7f-ac91f25ff9b5"),
                            Email = "caraka@usu.ac.id",
                            Name = "Caraka",
                            Password = "Caraka123"
                        },
                        new
                        {
                            Id = new Guid("6c82e5e9-e137-3935-cfc3-7b5842307d5c"),
                            Email = "carla@usu.ac.id",
                            Name = "Carla",
                            Password = "Carla123"
                        },
                        new
                        {
                            Id = new Guid("f3e4594b-1813-112a-bc70-5f902fcb40a9"),
                            Email = "makuta@usu.ac.id",
                            Name = "Makuta",
                            Password = "Makuta123"
                        },
                        new
                        {
                            Id = new Guid("1e9ecb9a-d577-95f9-4679-14160c6f56ee"),
                            Email = "banawa@usu.ac.id",
                            Name = "Banawa",
                            Password = "Banawa123"
                        },
                        new
                        {
                            Id = new Guid("11abe0b2-87b0-3bc0-fb38-13bfe034f5c8"),
                            Email = "asirwada@usu.ac.id",
                            Name = "Asirwada",
                            Password = "Asirwada123"
                        },
                        new
                        {
                            Id = new Guid("7d052ae8-6ddf-c9b9-5cae-ee05d6244439"),
                            Email = "cinthia@usu.ac.id",
                            Name = "Cinthia",
                            Password = "Cinthia123"
                        },
                        new
                        {
                            Id = new Guid("5b594793-6abc-f91a-8198-7a55700dea74"),
                            Email = "edi@usu.ac.id",
                            Name = "Edi",
                            Password = "Edi123"
                        },
                        new
                        {
                            Id = new Guid("a4ee2d9a-0862-bf55-29e3-57c873b1039d"),
                            Email = "kacung@usu.ac.id",
                            Name = "Kacung",
                            Password = "Kacung123"
                        },
                        new
                        {
                            Id = new Guid("9936f8d0-7777-f233-ba9d-d15103408558"),
                            Email = "gilda@usu.ac.id",
                            Name = "Gilda",
                            Password = "Gilda123"
                        },
                        new
                        {
                            Id = new Guid("c0749111-f02e-9b07-1de0-ebb66c962088"),
                            Email = "hilda@usu.ac.id",
                            Name = "Hilda",
                            Password = "Hilda123"
                        },
                        new
                        {
                            Id = new Guid("cd196e5d-4ddf-0f42-de55-6aaca5e69d52"),
                            Email = "artawan@usu.ac.id",
                            Name = "Artawan",
                            Password = "Artawan123"
                        },
                        new
                        {
                            Id = new Guid("2ce3192e-42cd-23c0-a345-fb359094fe4b"),
                            Email = "gilda@usu.ac.id",
                            Name = "Gilda",
                            Password = "Gilda123"
                        },
                        new
                        {
                            Id = new Guid("bfb472c4-3b4f-7734-cd88-1ccc076311a4"),
                            Email = "karja@usu.ac.id",
                            Name = "Karja",
                            Password = "Karja123"
                        },
                        new
                        {
                            Id = new Guid("7938f5a0-37d0-3e25-756f-cf4a36548740"),
                            Email = "galur@usu.ac.id",
                            Name = "Galur",
                            Password = "Galur123"
                        },
                        new
                        {
                            Id = new Guid("7ffe055a-cd5b-c51c-eb05-ecf633028248"),
                            Email = "puput@usu.ac.id",
                            Name = "Puput",
                            Password = "Puput123"
                        },
                        new
                        {
                            Id = new Guid("b763165f-945d-8615-50c1-64e3d647f93f"),
                            Email = "rini@usu.ac.id",
                            Name = "Rini",
                            Password = "Rini123"
                        },
                        new
                        {
                            Id = new Guid("7c961a8f-0ce1-e2f6-43d6-f91668db9975"),
                            Email = "rafi@usu.ac.id",
                            Name = "Rafi",
                            Password = "Rafi123"
                        },
                        new
                        {
                            Id = new Guid("242d7502-d49e-12d6-6370-915e2a4707b7"),
                            Email = "jati@usu.ac.id",
                            Name = "Jati",
                            Password = "Jati123"
                        },
                        new
                        {
                            Id = new Guid("99bdd58d-2d19-8843-324d-aa1016bdcb45"),
                            Email = "jono@usu.ac.id",
                            Name = "Jono",
                            Password = "Jono123"
                        },
                        new
                        {
                            Id = new Guid("c5d247a4-7c22-d264-1d83-f75c31dcfb54"),
                            Email = "kamaria@usu.ac.id",
                            Name = "Kamaria",
                            Password = "Kamaria123"
                        },
                        new
                        {
                            Id = new Guid("3d670304-d131-d70b-761c-dbebf2fe56bb"),
                            Email = "xanana@usu.ac.id",
                            Name = "Xanana",
                            Password = "Xanana123"
                        },
                        new
                        {
                            Id = new Guid("dd83b458-b487-9311-23a9-4bd7e28c540e"),
                            Email = "satya@usu.ac.id",
                            Name = "Satya",
                            Password = "Satya123"
                        },
                        new
                        {
                            Id = new Guid("a95ee212-0137-fc15-8667-28778d6fd3a6"),
                            Email = "sabrina@usu.ac.id",
                            Name = "Sabrina",
                            Password = "Sabrina123"
                        },
                        new
                        {
                            Id = new Guid("965d0089-94f0-39b5-243c-9fc74dcb8697"),
                            Email = "hasna@usu.ac.id",
                            Name = "Hasna",
                            Password = "Hasna123"
                        },
                        new
                        {
                            Id = new Guid("7fe68ec2-1a36-e6fa-a34a-8db8b0c01344"),
                            Email = "alambana@usu.ac.id",
                            Name = "Alambana",
                            Password = "Alambana123"
                        },
                        new
                        {
                            Id = new Guid("258f6470-9424-73a9-d71d-ad9bb94c1743"),
                            Email = "balapati@usu.ac.id",
                            Name = "Balapati",
                            Password = "Balapati123"
                        },
                        new
                        {
                            Id = new Guid("5dd6a668-5796-4ec7-e8dd-5e9c817abb61"),
                            Email = "ifa@usu.ac.id",
                            Name = "Ifa",
                            Password = "Ifa123"
                        },
                        new
                        {
                            Id = new Guid("79dec5a5-65a0-7220-ff08-6f9c17c55467"),
                            Email = "bahuwirya@usu.ac.id",
                            Name = "Bahuwirya",
                            Password = "Bahuwirya123"
                        },
                        new
                        {
                            Id = new Guid("4116a048-f490-6158-94b9-acf00286c815"),
                            Email = "garan@usu.ac.id",
                            Name = "Garan",
                            Password = "Garan123"
                        },
                        new
                        {
                            Id = new Guid("f15c59b5-358a-36a9-c029-35988f28c667"),
                            Email = "bagas@usu.ac.id",
                            Name = "Bagas",
                            Password = "Bagas123"
                        },
                        new
                        {
                            Id = new Guid("225d34e1-d92b-9732-8e80-fe7b6ec2dbf4"),
                            Email = "yono@usu.ac.id",
                            Name = "Yono",
                            Password = "Yono123"
                        },
                        new
                        {
                            Id = new Guid("454abf84-f70e-78f0-77a1-f452012e7ad5"),
                            Email = "lutfan@usu.ac.id",
                            Name = "Lutfan",
                            Password = "Lutfan123"
                        },
                        new
                        {
                            Id = new Guid("fcce2c0a-c0f4-f832-0dcd-33a91e8ca2ce"),
                            Email = "wirda@usu.ac.id",
                            Name = "Wirda",
                            Password = "Wirda123"
                        },
                        new
                        {
                            Id = new Guid("889d7d38-b143-8f35-124f-344b705bfb42"),
                            Email = "ciaobella@usu.ac.id",
                            Name = "Ciaobella",
                            Password = "Ciaobella123"
                        },
                        new
                        {
                            Id = new Guid("40f76385-ce54-2419-0dd6-e80c75b40255"),
                            Email = "langgeng@usu.ac.id",
                            Name = "Langgeng",
                            Password = "Langgeng123"
                        },
                        new
                        {
                            Id = new Guid("b0686d9e-2541-0793-cd06-7ee6187fbc47"),
                            Email = "saka@usu.ac.id",
                            Name = "Saka",
                            Password = "Saka123"
                        },
                        new
                        {
                            Id = new Guid("c3249cce-6b50-a9ba-973e-5a2edd54c371"),
                            Email = "dartono@usu.ac.id",
                            Name = "Dartono",
                            Password = "Dartono123"
                        },
                        new
                        {
                            Id = new Guid("5472b5a1-2113-8164-a1e7-cfe22e0e5930"),
                            Email = "oni@usu.ac.id",
                            Name = "Oni",
                            Password = "Oni123"
                        },
                        new
                        {
                            Id = new Guid("0cdce519-a962-8595-ecc9-74559f675504"),
                            Email = "wulan@usu.ac.id",
                            Name = "Wulan",
                            Password = "Wulan123"
                        },
                        new
                        {
                            Id = new Guid("318c0df3-9670-be84-7109-3e454f9d0609"),
                            Email = "devi@usu.ac.id",
                            Name = "Devi",
                            Password = "Devi123"
                        },
                        new
                        {
                            Id = new Guid("0268300b-541a-8f24-bd8b-ce7583da35e9"),
                            Email = "tirtayasa@usu.ac.id",
                            Name = "Tirtayasa",
                            Password = "Tirtayasa123"
                        },
                        new
                        {
                            Id = new Guid("e59a1db9-be4b-010e-db2a-b6ba388af454"),
                            Email = "calista@usu.ac.id",
                            Name = "Calista",
                            Password = "Calista123"
                        },
                        new
                        {
                            Id = new Guid("34d44e91-152a-dbb1-8529-26056b8926da"),
                            Email = "gatot@usu.ac.id",
                            Name = "Gatot",
                            Password = "Gatot123"
                        },
                        new
                        {
                            Id = new Guid("dbd7e894-7bdc-9b88-eeb1-475944d6a10f"),
                            Email = "dimaz@usu.ac.id",
                            Name = "Dimaz",
                            Password = "Dimaz123"
                        },
                        new
                        {
                            Id = new Guid("40b14aec-a835-7143-9db1-69c954054357"),
                            Email = "candrakanta@usu.ac.id",
                            Name = "Candrakanta",
                            Password = "Candrakanta123"
                        },
                        new
                        {
                            Id = new Guid("592b5b3c-c9af-9595-ebfc-31fc8e0997ee"),
                            Email = "amalia@usu.ac.id",
                            Name = "Amalia",
                            Password = "Amalia123"
                        },
                        new
                        {
                            Id = new Guid("febb6914-52d7-1ef6-f010-b07e8141b0d2"),
                            Email = "usyi@usu.ac.id",
                            Name = "Usyi",
                            Password = "Usyi123"
                        },
                        new
                        {
                            Id = new Guid("7fea28c5-7116-26af-3fdf-5a2f2f5a9e5a"),
                            Email = "bella@usu.ac.id",
                            Name = "Bella",
                            Password = "Bella123"
                        },
                        new
                        {
                            Id = new Guid("f610ae12-7b56-1f91-0440-700986e77189"),
                            Email = "natalia@usu.ac.id",
                            Name = "Natalia",
                            Password = "Natalia123"
                        },
                        new
                        {
                            Id = new Guid("49e9317e-aa57-4ca9-fd3a-acc88eb84c0f"),
                            Email = "adiarja@usu.ac.id",
                            Name = "Adiarja",
                            Password = "Adiarja123"
                        },
                        new
                        {
                            Id = new Guid("b704417f-dd98-f4e5-9fc4-ef4accae5c72"),
                            Email = "jati@usu.ac.id",
                            Name = "Jati",
                            Password = "Jati123"
                        },
                        new
                        {
                            Id = new Guid("41cdc211-9ad2-44df-9ad0-122014cd918b"),
                            Email = "admin@usu.ac.id",
                            Name = "Admin",
                            Password = "admin123"
                        },
                        new
                        {
                            Id = new Guid("107e9536-5fd4-4b44-891e-9e77eb5ca9ab"),
                            Email = "alvin@usu.ac.id",
                            Name = "Alvin",
                            Password = "alvin123"
                        },
                        new
                        {
                            Id = new Guid("6e8173db-65aa-4b55-b030-eee00927cd39"),
                            Email = "febriando@usu.ac.id",
                            Name = "Febriando",
                            Password = "febriando123"
                        });
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.Property<Guid>("AnsweredById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveysId")
                        .HasColumnType("uuid");

                    b.HasKey("AnsweredById", "SurveysId");

                    b.HasIndex("SurveysId");

                    b.ToTable("SurveyUser");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.SurveyQuestion", "SurveyQuestion")
                        .WithMany()
                        .HasForeignKey("SurveyQuestionSurveyId", "SurveyQuestionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", "Survey")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AnsweredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Navigation("SurveyQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
