// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Questionnaire.Infrastructure.Persistence.Postgres;

#nullable disable

namespace Questionnaire.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230530070922_LowercaseUserPassword")]
    partial class LowercaseUserPassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SurveyQuestionQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveyQuestionSurveyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionSurveyId", "SurveyQuestionQuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("218408d9-5277-4a87-85b0-49e4d58f562e"),
                            Advice = "memberikan kesempatan bertanya di dalam kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di dalam kelas?"
                        },
                        new
                        {
                            Id = new Guid("2345f1b9-68ea-47c0-a07c-308c96bb57f9"),
                            Advice = "memberikan kesempatan bertanya di luar kelas",
                            Section = "kesempatan bertanya",
                            Title = "Apakah dosen memberikan kesempatan bertanya di luar kelas?"
                        },
                        new
                        {
                            Id = new Guid("26a20919-c2a6-4d55-ba27-d1c9e7494803"),
                            Advice = "memanfaatkan fitur forum yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur forum e-learning?"
                        },
                        new
                        {
                            Id = new Guid("5eaade91-6711-40f4-bc93-865c1f236e9f"),
                            Advice = "memanfaatkan fitur kuis yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur kuis e-learning?"
                        },
                        new
                        {
                            Id = new Guid("92629cf6-7fe4-44fc-886e-96dc9fe7e46d"),
                            Advice = "memanfaatkan fitur konferensi video yang sudah tersedia",
                            Section = "penggunaan elearning",
                            Title = "Apakah dosen menggunakan fitur konferensi video e-learning?"
                        },
                        new
                        {
                            Id = new Guid("b242aabb-2a9b-4f6e-b5b2-c3f599ca307e"),
                            Advice = "memberikan nilai tugas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil tugas"
                        },
                        new
                        {
                            Id = new Guid("b69bc16e-ae97-471c-80db-6ef12b26638c"),
                            Advice = "memberikan nilai kuis secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil kuis"
                        },
                        new
                        {
                            Id = new Guid("c8d17dd4-ee70-4ab8-87d4-b5fff5b21e72"),
                            Advice = "memberikan nilai uts dan uas secara terbuka",
                            Section = "transparansi nilai",
                            Title = "Apakah dosen secara terbuka menyampaikan hasil uts dan uas"
                        },
                        new
                        {
                            Id = new Guid("d7434e14-1b4e-4d05-bc24-17c1fe75f4b9"),
                            Advice = "hadir tepat waktu (maksimal 15 menit keterlambatan)",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah dosen hadir tepat waktu"
                        },
                        new
                        {
                            Id = new Guid("dade9ae9-02b1-410c-9048-da7ed520c459"),
                            Advice = "memberikan perkuliahan sesuai dengan sesi yang sudah dialokasikan",
                            Section = "kedisiplinan waktu",
                            Title = "Apakah perkuliahan dilaksanakan sesuai dengan alokasi waktu"
                        },
                        new
                        {
                            Id = new Guid("dfddc352-89d5-40dc-a428-1cccd3bb1925"),
                            Advice = "menyampaikan materi sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah materi yang disampaikan sudah sesuai dengan rpp dan rps?"
                        },
                        new
                        {
                            Id = new Guid("f0b09e3c-87d1-4c8a-9408-cb9ee5881552"),
                            Advice = "memberikan tugas sesuai dengan kontrak kuliah",
                            Section = "rencana kontrak kuliah",
                            Title = "Apakah tugas yang diberikan sesuai dengan beban studi?"
                        },
                        new
                        {
                            Id = new Guid("fa5a6ef2-b376-4122-9f1e-591a29e1a2de"),
                            Advice = "mencari referensi terkait materi yang diajarkan",
                            Section = "penguasaan materi",
                            Title = "Apakah dosen menguasai materi perkuliahan dengan baik?"
                        });
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AspectCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("SurveyId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2f2fe42-f58c-1b99-2f18-97378f6402bf"),
                            Email = "daruna@usu.ac.id",
                            Name = "Daruna",
                            Password = "daruna123"
                        },
                        new
                        {
                            Id = new Guid("5717ae4b-bee7-440b-48f0-c9a616f01de6"),
                            Email = "ina@usu.ac.id",
                            Name = "Ina",
                            Password = "ina123"
                        },
                        new
                        {
                            Id = new Guid("acc7b522-cc9f-1832-6ad9-437dc931ab13"),
                            Email = "keisha@usu.ac.id",
                            Name = "Keisha",
                            Password = "keisha123"
                        },
                        new
                        {
                            Id = new Guid("cfc0ca26-680d-6862-ccf1-40baf5054b74"),
                            Email = "anom@usu.ac.id",
                            Name = "Anom",
                            Password = "anom123"
                        },
                        new
                        {
                            Id = new Guid("0a3334cb-e92e-93e5-a005-a994ec4eecf9"),
                            Email = "anita@usu.ac.id",
                            Name = "Anita",
                            Password = "anita123"
                        },
                        new
                        {
                            Id = new Guid("9ee668a7-31ad-bbd1-c845-c62a0dc5550e"),
                            Email = "hamzah@usu.ac.id",
                            Name = "Hamzah",
                            Password = "hamzah123"
                        },
                        new
                        {
                            Id = new Guid("b24aa6bf-fcb6-423d-2dd3-21c1f57c6218"),
                            Email = "bakti@usu.ac.id",
                            Name = "Bakti",
                            Password = "bakti123"
                        },
                        new
                        {
                            Id = new Guid("3900fa02-4322-045c-dab2-982257054947"),
                            Email = "jagaraga@usu.ac.id",
                            Name = "Jagaraga",
                            Password = "jagaraga123"
                        },
                        new
                        {
                            Id = new Guid("1e894e0b-f854-2795-2278-1dd72358358b"),
                            Email = "usyi@usu.ac.id",
                            Name = "Usyi",
                            Password = "usyi123"
                        },
                        new
                        {
                            Id = new Guid("c8004462-5e5b-9608-f94c-6e81328fa8da"),
                            Email = "amalia@usu.ac.id",
                            Name = "Amalia",
                            Password = "amalia123"
                        },
                        new
                        {
                            Id = new Guid("099df9bc-9e24-7aa4-6b58-d49d76f42826"),
                            Email = "dipa@usu.ac.id",
                            Name = "Dipa",
                            Password = "dipa123"
                        },
                        new
                        {
                            Id = new Guid("e6877feb-bc7d-935e-73ee-40436b772e06"),
                            Email = "nasrullah@usu.ac.id",
                            Name = "Nasrullah",
                            Password = "nasrullah123"
                        },
                        new
                        {
                            Id = new Guid("da0ebd6d-4d94-d9b4-84c6-76c14024a914"),
                            Email = "martani@usu.ac.id",
                            Name = "Martani",
                            Password = "martani123"
                        },
                        new
                        {
                            Id = new Guid("0b994793-cfd6-8adf-9933-3e064698188e"),
                            Email = "unjani@usu.ac.id",
                            Name = "Unjani",
                            Password = "unjani123"
                        },
                        new
                        {
                            Id = new Guid("cfcec852-015f-b28b-1015-9e87f08ec136"),
                            Email = "nabila@usu.ac.id",
                            Name = "Nabila",
                            Password = "nabila123"
                        },
                        new
                        {
                            Id = new Guid("3696f657-44fa-45ca-1c40-5802d157a43c"),
                            Email = "puspa@usu.ac.id",
                            Name = "Puspa",
                            Password = "puspa123"
                        },
                        new
                        {
                            Id = new Guid("3180027d-4782-cd46-2c4f-bb6273891b5f"),
                            Email = "cengkir@usu.ac.id",
                            Name = "Cengkir",
                            Password = "cengkir123"
                        },
                        new
                        {
                            Id = new Guid("63bca3af-04a1-2376-5bf7-05f9d055e003"),
                            Email = "puput@usu.ac.id",
                            Name = "Puput",
                            Password = "puput123"
                        },
                        new
                        {
                            Id = new Guid("e4b4a5d4-9e60-46a9-f597-6ef569a7aecb"),
                            Email = "putri@usu.ac.id",
                            Name = "Putri",
                            Password = "putri123"
                        },
                        new
                        {
                            Id = new Guid("6124c361-15bd-8d87-74d9-3ad184ed2692"),
                            Email = "nabila@usu.ac.id",
                            Name = "Nabila",
                            Password = "nabila123"
                        },
                        new
                        {
                            Id = new Guid("0ea949e4-ceb6-ba29-70b3-ff18e484363b"),
                            Email = "putu@usu.ac.id",
                            Name = "Putu",
                            Password = "putu123"
                        },
                        new
                        {
                            Id = new Guid("3e8a10f5-ace6-0d9f-8c4a-2ca5432ba309"),
                            Email = "kariman@usu.ac.id",
                            Name = "Kariman",
                            Password = "kariman123"
                        },
                        new
                        {
                            Id = new Guid("391bd872-52df-8e20-4ff1-723208248b42"),
                            Email = "gara@usu.ac.id",
                            Name = "Gara",
                            Password = "gara123"
                        },
                        new
                        {
                            Id = new Guid("7f9bc449-4656-22a9-b28a-4f9a7df330d3"),
                            Email = "yulia@usu.ac.id",
                            Name = "Yulia",
                            Password = "yulia123"
                        },
                        new
                        {
                            Id = new Guid("2fd37a11-e8a0-b5c1-e9f2-0a4632ce1ba3"),
                            Email = "samsul@usu.ac.id",
                            Name = "Samsul",
                            Password = "samsul123"
                        },
                        new
                        {
                            Id = new Guid("606de120-f908-b10f-254b-cc1e0543ce5d"),
                            Email = "bajragin@usu.ac.id",
                            Name = "Bajragin",
                            Password = "bajragin123"
                        },
                        new
                        {
                            Id = new Guid("f235716c-8913-0624-8f23-07ba80272717"),
                            Email = "raden@usu.ac.id",
                            Name = "Raden",
                            Password = "raden123"
                        },
                        new
                        {
                            Id = new Guid("5a533a0c-98cb-c560-3de7-162cc5394a59"),
                            Email = "cinthia@usu.ac.id",
                            Name = "Cinthia",
                            Password = "cinthia123"
                        },
                        new
                        {
                            Id = new Guid("5b4f362d-61a4-a776-9b3a-a04bd14ef6f4"),
                            Email = "gawati@usu.ac.id",
                            Name = "Gawati",
                            Password = "gawati123"
                        },
                        new
                        {
                            Id = new Guid("1d8aa52f-d01c-4e00-51e7-7e4aee00ab0f"),
                            Email = "martana@usu.ac.id",
                            Name = "Martana",
                            Password = "martana123"
                        },
                        new
                        {
                            Id = new Guid("ac4f48d7-7f15-0755-3854-efbbde58f2af"),
                            Email = "hamima@usu.ac.id",
                            Name = "Hamima",
                            Password = "hamima123"
                        },
                        new
                        {
                            Id = new Guid("ec6603b1-29fd-0902-7a4d-b43a838fba58"),
                            Email = "rina@usu.ac.id",
                            Name = "Rina",
                            Password = "rina123"
                        },
                        new
                        {
                            Id = new Guid("7a11064b-1c54-1f26-e98b-e88a9ccf7f02"),
                            Email = "baktianto@usu.ac.id",
                            Name = "Baktianto",
                            Password = "baktianto123"
                        },
                        new
                        {
                            Id = new Guid("98c50108-f03a-a3ac-5482-1dd46f913ecf"),
                            Email = "kawaya@usu.ac.id",
                            Name = "Kawaya",
                            Password = "kawaya123"
                        },
                        new
                        {
                            Id = new Guid("6f3c3e4a-bf1f-0cd6-2a3d-9a572102da6c"),
                            Email = "faizah@usu.ac.id",
                            Name = "Faizah",
                            Password = "faizah123"
                        },
                        new
                        {
                            Id = new Guid("041e6e7c-c9d1-e3b8-9787-21008b5a9a07"),
                            Email = "putri@usu.ac.id",
                            Name = "Putri",
                            Password = "putri123"
                        },
                        new
                        {
                            Id = new Guid("c23498d8-d011-7a3e-b229-c45bf0d7f45f"),
                            Email = "tiara@usu.ac.id",
                            Name = "Tiara",
                            Password = "tiara123"
                        },
                        new
                        {
                            Id = new Guid("83233fa5-8445-1a7c-0c29-3a793430567b"),
                            Email = "daliman@usu.ac.id",
                            Name = "Daliman",
                            Password = "daliman123"
                        },
                        new
                        {
                            Id = new Guid("02d2e5fe-f30a-49b8-2a07-c1ffbb66568d"),
                            Email = "eka@usu.ac.id",
                            Name = "Eka",
                            Password = "eka123"
                        },
                        new
                        {
                            Id = new Guid("4e34df7b-5dca-4298-344a-fb9187e5f731"),
                            Email = "balamantri@usu.ac.id",
                            Name = "Balamantri",
                            Password = "balamantri123"
                        },
                        new
                        {
                            Id = new Guid("cc4bb1d9-f6ed-0bed-6af5-478b949ce593"),
                            Email = "wirda@usu.ac.id",
                            Name = "Wirda",
                            Password = "wirda123"
                        },
                        new
                        {
                            Id = new Guid("d1ac3a39-0dbb-1059-c1bc-257a9a5062d6"),
                            Email = "kania@usu.ac.id",
                            Name = "Kania",
                            Password = "kania123"
                        },
                        new
                        {
                            Id = new Guid("177706b8-b9b1-3ec9-53ab-2cec6d665be6"),
                            Email = "martaka@usu.ac.id",
                            Name = "Martaka",
                            Password = "martaka123"
                        },
                        new
                        {
                            Id = new Guid("c5e5f19f-a325-b546-e8f3-49f70ccc6766"),
                            Email = "eli@usu.ac.id",
                            Name = "Eli",
                            Password = "eli123"
                        },
                        new
                        {
                            Id = new Guid("1b2d537b-b26f-4636-a5bb-7148c79cadef"),
                            Email = "muhammad@usu.ac.id",
                            Name = "Muhammad",
                            Password = "muhammad123"
                        },
                        new
                        {
                            Id = new Guid("9ad21dd4-0dc6-212f-3647-02b69214c34e"),
                            Email = "surya@usu.ac.id",
                            Name = "Surya",
                            Password = "surya123"
                        },
                        new
                        {
                            Id = new Guid("376ed614-4382-007f-4b11-99650f83928b"),
                            Email = "tina@usu.ac.id",
                            Name = "Tina",
                            Password = "tina123"
                        },
                        new
                        {
                            Id = new Guid("d4259f7f-5241-d908-38ef-9eb6b5008e4b"),
                            Email = "devi@usu.ac.id",
                            Name = "Devi",
                            Password = "devi123"
                        },
                        new
                        {
                            Id = new Guid("21c18bfb-3214-5d4c-4f02-f8d6943b8d25"),
                            Email = "bakidin@usu.ac.id",
                            Name = "Bakidin",
                            Password = "bakidin123"
                        },
                        new
                        {
                            Id = new Guid("928f2854-be38-5226-da7f-ed8f3a3c6dc8"),
                            Email = "margana@usu.ac.id",
                            Name = "Margana",
                            Password = "margana123"
                        },
                        new
                        {
                            Id = new Guid("112a5cad-4c58-f898-d321-ef27141e6b09"),
                            Email = "cinthia@usu.ac.id",
                            Name = "Cinthia",
                            Password = "cinthia123"
                        },
                        new
                        {
                            Id = new Guid("beb97497-afa4-7c5f-8c43-840a177d8373"),
                            Email = "erik@usu.ac.id",
                            Name = "Erik",
                            Password = "erik123"
                        },
                        new
                        {
                            Id = new Guid("3280b0b0-a7bc-0b9b-546e-96600a8940ef"),
                            Email = "bagya@usu.ac.id",
                            Name = "Bagya",
                            Password = "bagya123"
                        },
                        new
                        {
                            Id = new Guid("eab97f9a-3442-92e9-9024-73fdcb4ad275"),
                            Email = "kurnia@usu.ac.id",
                            Name = "Kurnia",
                            Password = "kurnia123"
                        },
                        new
                        {
                            Id = new Guid("242fc5a7-154b-52ca-93e4-156ed97cb365"),
                            Email = "gabriella@usu.ac.id",
                            Name = "Gabriella",
                            Password = "gabriella123"
                        },
                        new
                        {
                            Id = new Guid("3d8af3d9-6213-bd6b-4efb-ee36145f725a"),
                            Email = "nadia@usu.ac.id",
                            Name = "Nadia",
                            Password = "nadia123"
                        },
                        new
                        {
                            Id = new Guid("af19fb59-b9f0-4393-bf68-3501c92faa84"),
                            Email = "bakiman@usu.ac.id",
                            Name = "Bakiman",
                            Password = "bakiman123"
                        },
                        new
                        {
                            Id = new Guid("749cfa0e-fa1d-d2fe-55c8-f2e299a663c5"),
                            Email = "ilsa@usu.ac.id",
                            Name = "Ilsa",
                            Password = "ilsa123"
                        },
                        new
                        {
                            Id = new Guid("c31da94c-cdef-f30a-46ed-45a1d3cf5572"),
                            Email = "soleh@usu.ac.id",
                            Name = "Soleh",
                            Password = "soleh123"
                        },
                        new
                        {
                            Id = new Guid("4210ce2e-6d8c-ee55-fe7f-9b5f663fee6c"),
                            Email = "uli@usu.ac.id",
                            Name = "Uli",
                            Password = "uli123"
                        },
                        new
                        {
                            Id = new Guid("14e21d6e-e54d-020b-b4c5-4bdd1329e74d"),
                            Email = "faizah@usu.ac.id",
                            Name = "Faizah",
                            Password = "faizah123"
                        },
                        new
                        {
                            Id = new Guid("4fd1c096-cb21-aedb-d6f1-583d6bcfbe53"),
                            Email = "tiara@usu.ac.id",
                            Name = "Tiara",
                            Password = "tiara123"
                        },
                        new
                        {
                            Id = new Guid("7d09be6c-45ad-7798-58b7-9d79f7b6e7c5"),
                            Email = "tugiman@usu.ac.id",
                            Name = "Tugiman",
                            Password = "tugiman123"
                        },
                        new
                        {
                            Id = new Guid("f7d64bce-588a-4b72-89a2-0ad4d56d273b"),
                            Email = "harto@usu.ac.id",
                            Name = "Harto",
                            Password = "harto123"
                        },
                        new
                        {
                            Id = new Guid("a63371c1-19ef-9840-a293-017e5489e471"),
                            Email = "ridwan@usu.ac.id",
                            Name = "Ridwan",
                            Password = "ridwan123"
                        },
                        new
                        {
                            Id = new Guid("0b965591-a0dd-e4a2-da95-49e0f4f8ed8b"),
                            Email = "kasusra@usu.ac.id",
                            Name = "Kasusra",
                            Password = "kasusra123"
                        },
                        new
                        {
                            Id = new Guid("be7053f1-ee19-e1b1-3bed-c4b0ee5c1c96"),
                            Email = "sadina@usu.ac.id",
                            Name = "Sadina",
                            Password = "sadina123"
                        },
                        new
                        {
                            Id = new Guid("893ced23-516a-942b-b696-b812d7adc5c5"),
                            Email = "wulan@usu.ac.id",
                            Name = "Wulan",
                            Password = "wulan123"
                        },
                        new
                        {
                            Id = new Guid("ef816050-c1cc-fa20-db23-a30bda1d30a3"),
                            Email = "ilyas@usu.ac.id",
                            Name = "Ilyas",
                            Password = "ilyas123"
                        },
                        new
                        {
                            Id = new Guid("bd7ef19b-8b2e-57e9-b3f6-95dc917f3247"),
                            Email = "endah@usu.ac.id",
                            Name = "Endah",
                            Password = "endah123"
                        },
                        new
                        {
                            Id = new Guid("dc5d4699-9e4e-61ab-fbb4-81bd28579621"),
                            Email = "unjani@usu.ac.id",
                            Name = "Unjani",
                            Password = "unjani123"
                        },
                        new
                        {
                            Id = new Guid("e9fc9137-2df0-660b-3f47-07f47e3985da"),
                            Email = "prakosa@usu.ac.id",
                            Name = "Prakosa",
                            Password = "prakosa123"
                        },
                        new
                        {
                            Id = new Guid("ac29b6c4-7ba6-874d-154e-7a97a8a7fadc"),
                            Email = "carub@usu.ac.id",
                            Name = "Carub",
                            Password = "carub123"
                        },
                        new
                        {
                            Id = new Guid("6151d401-41e0-0675-c582-69b0715a3bdf"),
                            Email = "salsabila@usu.ac.id",
                            Name = "Salsabila",
                            Password = "salsabila123"
                        },
                        new
                        {
                            Id = new Guid("426702aa-9961-3f8b-9368-6b089365f1fd"),
                            Email = "ciaobella@usu.ac.id",
                            Name = "Ciaobella",
                            Password = "ciaobella123"
                        },
                        new
                        {
                            Id = new Guid("cf0a32c2-bd6d-933e-1ac9-3d34a272e597"),
                            Email = "empluk@usu.ac.id",
                            Name = "Empluk",
                            Password = "empluk123"
                        },
                        new
                        {
                            Id = new Guid("f21d740a-18b7-ce3e-4551-e52ad5bf2b4a"),
                            Email = "bella@usu.ac.id",
                            Name = "Bella",
                            Password = "bella123"
                        },
                        new
                        {
                            Id = new Guid("6c4f1819-0244-985a-467e-1a390c1321e3"),
                            Email = "martaka@usu.ac.id",
                            Name = "Martaka",
                            Password = "martaka123"
                        },
                        new
                        {
                            Id = new Guid("3ebbc9bf-a81e-f715-e88b-80d0ff13f8a9"),
                            Email = "jaswadi@usu.ac.id",
                            Name = "Jaswadi",
                            Password = "jaswadi123"
                        },
                        new
                        {
                            Id = new Guid("0f7a07e4-7ea8-0cff-d46f-ccda2dfd21bc"),
                            Email = "wisnu@usu.ac.id",
                            Name = "Wisnu",
                            Password = "wisnu123"
                        },
                        new
                        {
                            Id = new Guid("ce0e6810-56f6-6873-978f-a9696e424f96"),
                            Email = "azalea@usu.ac.id",
                            Name = "Azalea",
                            Password = "azalea123"
                        },
                        new
                        {
                            Id = new Guid("17a8c2b2-9ce1-413d-7d3a-26d2d4f17ab0"),
                            Email = "titin@usu.ac.id",
                            Name = "Titin",
                            Password = "titin123"
                        },
                        new
                        {
                            Id = new Guid("80152164-c797-8d7a-3b87-0b4853ac4313"),
                            Email = "baktiono@usu.ac.id",
                            Name = "Baktiono",
                            Password = "baktiono123"
                        },
                        new
                        {
                            Id = new Guid("c71c2af3-23a7-cb90-4338-ab805a471131"),
                            Email = "harto@usu.ac.id",
                            Name = "Harto",
                            Password = "harto123"
                        },
                        new
                        {
                            Id = new Guid("8ab54453-ec46-7340-e66f-afde9137ca0a"),
                            Email = "kuncara@usu.ac.id",
                            Name = "Kuncara",
                            Password = "kuncara123"
                        },
                        new
                        {
                            Id = new Guid("e404ac81-31fe-8be6-ad44-b3c5b3a78355"),
                            Email = "vinsen@usu.ac.id",
                            Name = "Vinsen",
                            Password = "vinsen123"
                        },
                        new
                        {
                            Id = new Guid("854a01fa-bd1a-d5d9-c528-ecc376c110a8"),
                            Email = "puji@usu.ac.id",
                            Name = "Puji",
                            Password = "puji123"
                        },
                        new
                        {
                            Id = new Guid("c49782bb-c3c9-a79e-e909-5e92fbfd5d1c"),
                            Email = "bakda@usu.ac.id",
                            Name = "Bakda",
                            Password = "bakda123"
                        },
                        new
                        {
                            Id = new Guid("ed507dd9-5744-0d46-926e-c56010bc8b59"),
                            Email = "maimunah@usu.ac.id",
                            Name = "Maimunah",
                            Password = "maimunah123"
                        },
                        new
                        {
                            Id = new Guid("055d0078-98f9-29fc-8cd5-714352c801a0"),
                            Email = "vivi@usu.ac.id",
                            Name = "Vivi",
                            Password = "vivi123"
                        },
                        new
                        {
                            Id = new Guid("7ca088f5-f876-f656-4499-9dc53f77f3fe"),
                            Email = "jane@usu.ac.id",
                            Name = "Jane",
                            Password = "jane123"
                        },
                        new
                        {
                            Id = new Guid("31ba9229-7054-fcb6-636f-4eda2cb5c45c"),
                            Email = "rosman@usu.ac.id",
                            Name = "Rosman",
                            Password = "rosman123"
                        },
                        new
                        {
                            Id = new Guid("b3357877-b474-ab6d-f270-95ac5d3e9234"),
                            Email = "paulin@usu.ac.id",
                            Name = "Paulin",
                            Password = "paulin123"
                        },
                        new
                        {
                            Id = new Guid("e5f88e8f-7110-b772-9235-eda5b1dbd509"),
                            Email = "harsana@usu.ac.id",
                            Name = "Harsana",
                            Password = "harsana123"
                        },
                        new
                        {
                            Id = new Guid("b729da39-c386-5fb1-c5d6-47543717fb34"),
                            Email = "bella@usu.ac.id",
                            Name = "Bella",
                            Password = "bella123"
                        },
                        new
                        {
                            Id = new Guid("40cbcac1-d4be-4d8a-ff12-12e2cbba8e08"),
                            Email = "martaka@usu.ac.id",
                            Name = "Martaka",
                            Password = "martaka123"
                        },
                        new
                        {
                            Id = new Guid("534caef9-11ca-0cda-19ab-90ede322338f"),
                            Email = "jagaraga@usu.ac.id",
                            Name = "Jagaraga",
                            Password = "jagaraga123"
                        },
                        new
                        {
                            Id = new Guid("41cdc211-9ad2-44df-9ad0-122014cd918b"),
                            Email = "admin@usu.ac.id",
                            Name = "Admin",
                            Password = "admin123"
                        },
                        new
                        {
                            Id = new Guid("107e9536-5fd4-4b44-891e-9e77eb5ca9ab"),
                            Email = "alvin@usu.ac.id",
                            Name = "Alvin",
                            Password = "alvin123"
                        },
                        new
                        {
                            Id = new Guid("6e8173db-65aa-4b55-b030-eee00927cd39"),
                            Email = "febriando@usu.ac.id",
                            Name = "Febriando",
                            Password = "febriando123"
                        });
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.Property<Guid>("AnsweredById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveysId")
                        .HasColumnType("uuid");

                    b.HasKey("AnsweredById", "SurveysId");

                    b.HasIndex("SurveysId");

                    b.ToTable("SurveyUser");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.SurveyQuestion", "SurveyQuestion")
                        .WithMany()
                        .HasForeignKey("SurveyQuestionSurveyId", "SurveyQuestionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", "Survey")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.HasOne("Questionnaire.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AnsweredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Questionnaire.Domain.Entities.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Questionnaire.Domain.Entities.Survey", b =>
                {
                    b.Navigation("SurveyQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
